### ISSUE TITLE
error when creating import job

### ISSUE THREAD

**Issue by mdlaat** [matomo-org/plugin-GoogleAnalyticsImporter#104]
Hello, thank you for matomo and this plugin.
Trying to import GA to matomo on my wordpress site.
When creating an import job, I get the error in dutch, which translates to:
date format should be yyyy-mm-dd, or today or yesterday or any keyword supported by the strtotime function

This is when leaving the two date fields empty, but also when populating these two fields with something in the format yyyy-mm-dd

Can a kind person help me with this one?
Thank you & kind regards

**Comment by tsteur** [comment]
fyi another user just reported the same by email.

**Comment by diosmosis** [comment]
Should be fixed by #117
