### ISSUE TITLE
Respect API error 429 with exponential back-off

### ISSUE THREAD

**Issue by RickyRomero** [matomo-org/plugin-GoogleAnalyticsImporter#11]
After getting data import working using the command line (see #10), I quickly encountered an API rate limit issue that isn't being handled correctly.

```
[...]
DEBUG [2019-10-31 04:29:55] 23168  Importing data for the VisitsSummary plugin.
INFO [2019-10-31 04:29:55] 23168  Found 0 sessions for 2010-02-27, skipping rest of plugins for this day.
INFO [2019-10-31 04:29:55] 23168  Importing data for GA View 32780573 for date 2010-02-28...
DEBUG [2019-10-31 04:29:55] 23168  Importing data for the VisitsSummary plugin.
DEBUG [2019-10-31 04:29:55] 23168  Google Analytics returned an error: {
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota group 'AnalyticsDefaultGroup' and limit 'USER-100s' of service 'analyticsreporting.googleapis.com' for consumer 'project_number:1055142121829'.",
    "errors": [
      {
        "message": "Quota exceeded for quota group 'AnalyticsDefaultGroup' and limit 'USER-100s' of service 'analyticsreporting.googleapis.com' for consumer 'project_number:1055142121829'.",
        "domain": "global",
        "reason": "rateLimitExceeded"
      }
    ],
    "status": "RESOURCE_EXHAUSTED"
  }
}

DEBUG [2019-10-31 04:29:56] 23168  Google Analytics returned an error: {
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota group 'AnalyticsDefaultGroup' and limit 'USER-100s' of service 'analyticsreporting.googleapis.com' for consumer 'project_number:1055142121829'.",
    "errors": [
      {
        "message": "Quota exceeded for quota group 'AnalyticsDefaultGroup' and limit 'USER-100s' of service 'analyticsreporting.googleapis.com' for consumer 'project_number:1055142121829'.",
        "domain": "global",
        "reason": "rateLimitExceeded"
      }
    ],
    "status": "RESOURCE_EXHAUSTED"
  }
}
[...]
```

These 429 errors continued until I stopped the script.

[According to the Analytics Reporting API documentation](https://developers.google.com/analytics/devguides/reporting/core/v4/errors?hl=en_US), the `USER-100s` error means we're sending requests too fast. There doesn't appear to be a way to manually throttle them in the plugin. The API docs recommend implementing [exponential back-off](https://developers.google.com/analytics/devguides/reporting/core/v4/errors?hl=en_US#backoff) to resolve the issue.

**Comment by diosmosis** [comment]
The plugin waits if 429 errors continue, however the USER-100s limit doesn't appear to really be 10 requests per 100s. We could probably wait longer in between requests, though (how long did you wait before stopping the script?).

Note: There is also a 50,000 daily request limit that will be reached at around 4 months of data. Imports are started and stopped through scheduled tasks and will be picked up again the next day when a limit like that is reached.
