### ISSUE TITLE
Missing Data in Month & Year Reports for Imported Date Range

### ISSUE THREAD

**Issue by danieljwonder** [matomo-org/plugin-GoogleAnalyticsImporter#111]
I recently completed an import job between 2009 - 2020 but no data is shown within any **month** or **year** evolution graphs or summary cards within Matomo between 2011 - 2017 despite there being lots of data available within this range when viewing a daily report. 

![monthly-bug](https://user-images.githubusercontent.com/2772782/91007724-cd92f380-e630-11ea-9606-5404dc043d16.png)

When reviewing an arbitrary day report within this range, e.g. 2015-08-14 the report shows data does exist at the daily level. 

![daily-bug](https://user-images.githubusercontent.com/2772782/91007738-d4216b00-e630-11ea-89ab-2d73dd5d0d6d.png)

@mattab confirmed via email that this is likely a bug and asked me to report here. 

The monthly data appears to stop in Feb 2010 and begin again in June 2018 which is a little over two years ago if that has any relevance?

While attempting to understand what might be happening, I ran a console command to invalidate the data to see whether this would regenerate the reports but it didn't appear to have an effect.

`./console core:invalidate-report-data --dates=2009-01-01,2018-06-30 --sites=5`

**Comment by danieljwonder** [comment]
The same issue has occurred on another site I ran the import on, within the same Matomo instance. Except, in this case, the gap is between 2015 and July 2018.

EDIT: Based on the fact this data started again a month later and the import finished about a month later I looked into retention policy and noticed this was set to just over two years which would seem to line up so it may be user error. I'm still not sure why days would show but not months or years?

**Comment by diosmosis** [comment]
Hi @danielmcclure, sorry you're experiencing this issue. Can you try running the archiving command like this:

```
./console core:archive --force-idsites=<idSite> --force-date-range=2018-06-01,2018-06-30 --force-periods=month
```

for a range w/ no month data but day & week data, and see if the month data shows up?

**Comment by danieljwonder** [comment]
Skipping archiving for website id = 7, period = month, date = 2018-06-01,2018-06-30, segment = , since there is already a valid archive (tracking a visit automatically invalidates archives).

**Comment by diosmosis** [comment]
@danielmcclure and there's no data for that month, but there is data for the days/weeks in that month, correct? Could you execute the following API requests, and post what you get:

```
http://yourmatomo.com/index.php?module=API&method=VisitsSummary.get&period=month&date=2018-06-10&idSite=...&token_auth=...

http://yourmatomo.com/index.php?module=API&method=VisitsSummary.get&period=week&date=2018-06-10&idSite=...&token_auth=...

http://yourmatomo.com/index.php?module=API&method=VisitsSummary.get&period=day&date=2018-06-10&idSite=...&token_auth=...
```

(with the idSite & token_auth parameters replaced)

**Comment by saschanos** [comment]
Experiencing the same issue. For all days the importer was active for a specific, there's no data which was directly tracked by Matomo shown in the graphs (but there's data existing). After I stopped importing, data for these days is correctly imported. Is there any way to fix the reports? I already deleted the reports and forced to rebuild them – with no success.

**Comment by diosmosis** [comment]
@saschanos would you be willing to provide access to your matomo instance? If so can you create a new user with access to the imported site and provide credentials to support@matomo.org?

**Comment by saschanos** [comment]
@diosmosis, sent two mails to this mail address – did not receive any response 👎

**Comment by diosmosis** [comment]
Hi @saschanos, the question you sent isn't one I can answer as I am a developer. I forwarded it to the person who can.

EDIT: do note, this person is far busier than I am and prioritizes paid support.

**Comment by danieljwonder** [comment]
https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/issues/111#issuecomment-682286632

**Year/Month/Week**
```
<result>
<nb_visits>0</nb_visits>
<nb_actions>0</nb_actions>
<nb_visits_converted>0</nb_visits_converted>
<bounce_count>0</bounce_count>
<sum_visit_length>0</sum_visit_length>
<max_actions>0</max_actions>
<bounce_rate>0%</bounce_rate>
<nb_actions_per_visit>0</nb_actions_per_visit>
<avg_time_on_site>0</avg_time_on_site>
</result>
```

**Day**
```
<result>
<nb_uniq_visitors>40</nb_uniq_visitors>
<nb_users>0</nb_users>
<nb_visits>41</nb_visits>
<nb_actions>106</nb_actions>
<nb_visits_converted>1</nb_visits_converted>
<bounce_count>1</bounce_count>
<sum_visit_length>2195</sum_visit_length>
<max_actions>0</max_actions>
<bounce_rate>2%</bounce_rate>
<nb_actions_per_visit>2.6</nb_actions_per_visit>
<avg_time_on_site>54</avg_time_on_site>
</result>
```
Re-import appears to be fixing it.

**Comment by saschanos** [comment]
Looks like the InnoCraft team found a fix for the problem – there will be an update in a few days :).

**Comment by danieljwonder** [comment]
Fixed 👍
