### ISSUE TITLE
Custom dimension import fails: Invalid value '' for 'active' specified. 

### ISSUE THREAD

**Issue by tsteur** [matomo-org/plugin-GoogleAnalyticsImporter#115]
@diosmosis this might be an easy fix?

should the API return null could maybe default to false or true?

> Error: {"message":"Invalid value '' for 'active' specified. Allowed values: '0' or '1'","file":"\/plugins\/CustomDimensions\/Dimension\/Active.php","line":27,"backtrace":" on \/plugins\/CustomDimensions\/Dimension\/Active.php(27)\n#0 \/plugins\/CustomDimensions\/API.php(225): Piwik\\Plugins\\CustomDimensions\\Dimension\\Active->check()\n#1 \/plugins\/CustomDimensions\/API.php(107): Piwik\\Plugins\\CustomDimensions\\API->checkCustomDimensionConfig(Object(Piwik\\Plugins\\CustomDimensions\\Dimension\\Name), Object(Piwik\\Plugins\\CustomDimensions\\Dimension\\Active), Array, true)\n#2 \/plugins\/GoogleAnalyticsImporter\/Importer.php(291): Piwik\\Plugins\\CustomDimensions\\API->configureNewCustomDimension('2', 'thename', 'action', NULL, Array, true)\n#3 \/plugins\/GoogleAnalyticsImporter\/Importer.php(195): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importer->importCustomDimensions('2', 'xxxxxx', 'UA-xxxxxx-1')\n#4 \/plugins\/GoogleAnalyticsImporter\/Commands\/ImportReports.php(174): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importer->importEntities('2', 'xxxxxx', 'UA-xxxxxx-1', 'yyyyyyy')\n#5 \/vendor\/symfony\/console\/Symfony\/Component\/Console\/Command\/Command.php(257): Piwik\\Plugins\\GoogleAnalyticsImporter\\Commands\\ImportReports->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#6 \/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(874): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#7 \/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(195): Symfony\\Component\\Console\\Application->doRunCommand(Object(Piwik\\Plugins\\GoogleAnalyticsImporter\\Commands\\ImportReports), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 [internal function]: Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 \/core\/Console.php(140): call_user_func(Array, Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/core\/Access.php(644): Piwik\\Console->Piwik\\{closure}()\n#11 \/core\/Console.php(141): Piwik\\Access::doAsSuperUser(Object(Closure))\n#12 \/core\/Console.php(93): Piwik\\Console->doRunImpl(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 \/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(126): Piwik\\Console->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 \/console(32): Symfony\\Component\\Console\\Application->run()\n#15 {main}"}

**Comment by diosmosis** [comment]
Fixed by #118
