### ISSUE TITLE
JS error when trying to start import

### ISSUE THREAD

**Issue by tsteur** [matomo-org/plugin-GoogleAnalyticsImporter#126]
![image](https://user-images.githubusercontent.com/273120/91926131-a9b76800-ed2a-11ea-8aba-5b3bbb067316.png)

seems related to invalid end date? BTW it also doesn't say what the expected format is.

**Comment by diosmosis** [comment]
The second parameter is supposed to be an array. I was sure I fixed this...

**Comment by diosmosis** [comment]
Fixed by #127
