### ISSUE TITLE
Failed to reach GA after 30 attempts. Restart the import later.

### ISSUE THREAD

**Issue by mattab** [matomo-org/plugin-GoogleAnalyticsImporter#131]
Note: this is running the previous 1.5.3 version of the plugin. 

Getting this error very often, every 5min or more often:

> Failed to reach GA after 30 attempts. Restart the import later.

Error: {"message":"Failed to reach GA after 30 attempts. Restart the import later.","file":"\/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Google\/GoogleAnalyticsQueryService.php","line":214,"backtrace":" on \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Google\/GoogleAnalyticsQueryService.php(214)\n#0 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Google\/GoogleAnalyticsQueryService.php(106): Piwik\\Plugins\\GoogleAnalyticsImporter\\Google\\GoogleAnalyticsQueryService->gaBatchGet(Object(Piwik\\Date), Array, Array, 'ga:sessions')\n#1 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Importers\/Referrers\/RecordImporter.php(125): Piwik\\Plugins\\GoogleAnalyticsImporter\\Google\\GoogleAnalyticsQueryService->query(Object(Piwik\\Date), Array, Array)\n#2 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Importers\/Referrers\/RecordImporter.php(69): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importers\\Referrers\\RecordImporter->getKeywordByCampaign(Object(Piwik\\Date))\n#3 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Importer.php(432): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importers\\Referrers\\RecordImporter->importRecords(Object(Piwik\\Date))\n#4 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Importer.php(369): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importer->importDay(Object(Piwik\\Site), Object(Piwik\\Date), Array, '')\n#5 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Commands\/ImportReports.php(243): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importer->import('21', '167675787', Object(Piwik\\Date), Object(Piwik\\Date), Object(Piwik\\Plugins\\GoogleAnalyticsImporter\\ImportLock))\n#6 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Command\/Command.php(257): Piwik\\Plugins\\GoogleAnalyticsImporter\\Commands\\ImportReports->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#7 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(874): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(195): Symfony\\Component\\Console\\Application->doRunCommand(Object(Piwik\\Plugins\\GoogleAnalyticsImporter\\Commands\\ImportReports), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 [internal function]: Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/var\/www\/html\/core\/Console.php(140): call_user_func(Array, Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/var\/www\/html\/core\/Access.php(644): Piwik\\Console->Piwik\\{closure}()\n#12 \/var\/www\/html\/core\/Console.php(141): Piwik\\Access::doAsSuperUser(Object(Closure))\n#13 \/var\/www\/html\/core\/Console.php(93): Piwik\\Console->doRunImpl(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(126): Piwik\\Console->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 \/var\/www\/html\/console(32): Symfony\\Component\\Console\\Application->run()\n#16 {main}"}

**Comment by mattab** [comment]
Can we not error out so the crontab doesn't email us?

update: Note: this is running the previous 1.5.3 version of the plugin.

**Comment by diosmosis** [comment]
@mattab this shouldn't happen w/ the latest version, can you check again?

**Comment by mattab** [comment]
Confirmed it's fixed :+1:
