### ISSUE TITLE
Error: Token has been expired or revoked.

### ISSUE THREAD

**Issue by mattab** [matomo-org/plugin-GoogleAnalyticsImporter#132]
> "message":"{\n \"error\": \"invalid_grant\",\n \"error_description\": \"Token has been expired or revoked.\

Can we not error out so the crontab doesn't email us?

Error: {"message":"{\n  \"error\": \"invalid_grant\",\n  \"error_description\": \"Token has been expired or revoked.\"\n}","file":"\/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php","line":118,"backtrace":" on \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(118)\n#0 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\\Psr7\\Response), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#1 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Task\/Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\\Client), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#2 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(58): Google_Task_Runner->run()\n#3 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Client.php(862): Google_Http_REST::execute(Object(GuzzleHttp\\Client), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...', Array, NULL)\n#4 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Service\/Resource.php(232): Google_Client->execute(Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#5 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient-services\/src\/Google\/Service\/Analytics\/Resource\/ManagementGoals.php(84): Google_Service_Resource->call('list', Array, 'Google_Service_...')\n#6 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Importer.php(213): Google_Service_Analytics_Resource_ManagementGoals->listManagementGoals('xxxx 'UA-XXX-1', 'XXX')\n#7 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Importer.php(194): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importer->importGoals('2', 'XXX', 'UA-XXX-1', 'XXXX')\n#8 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Commands\/ImportReports.php(174): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importer->importEntities('2', 'XXX', 'UA-XXX-1', '80769682')\n#9 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Command\/Command.php(257): Piwik\\Plugins\\GoogleAnalyticsImporter\\Commands\\ImportReports->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(874): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(195): Symfony\\Component\\Console\\Application->doRunCommand(Object(Piwik\\Plugins\\GoogleAnalyticsImporter\\Commands\\ImportReports), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 [internal function]: Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 \/var\/www\/html\/core\/Console.php(140): call_user_func(Array, Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 \/var\/www\/html\/core\/Access.php(644): Piwik\\Console->Piwik\\{closure}()\n#15 \/var\/www\/html\/core\/Console.php(141): Piwik\\Access::doAsSuperUser(Object(Closure))\n#16 \/var\/www\/html\/core\/Console.php(93): Piwik\\Console->doRunImpl(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(126): Piwik\\Console->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 \/var\/www\/html\/console(32): Symfony\\Component\\Console\\Application->run()\n#19 {main}"}

**Comment by mattab** [comment]
Note: this is running the previous 1.5.3 version of the plugin.

**Comment by diosmosis** [comment]
@mattab this shouldn't happen w/ the latest version, can you check again?

**Comment by mattab** [comment]
Works now :+1:
