### ISSUE TITLE
Page Urls show __mtm_ga_default_name_placeholder__ 

### ISSUE THREAD

**Issue by mattab** [matomo-org/plugin-GoogleAnalyticsImporter#140]
Reported by email

    Currently we have the following URLs, which were imported:

      /en/__mtm_ga_default_name_placeholder__#utm_source=xxxxx

      It looks like the parameter: __mtm_ga_default_name_placeholder_ does not belong here. Will this be cleaned up?

![Screenshot from 2020-10-08 16-04-45](https://user-images.githubusercontent.com/466765/95410287-06d4b800-0980-11eb-9c5b-6d089eec6c3c.png)

**Comment by diosmosis** [comment]
Fixed by #142
