### ISSUE TITLE
[Exception] Import was cancelled

### ISSUE THREAD

**Issue by wcz-txp** [matomo-org/plugin-GoogleAnalyticsImporter#146]
Hello,
I'm stuck with importing older data from Google Analytics into existing sites in my Matomo installation.
After successfully importing data for one site, I tried to import the data for other sites.
To import these data, I use the following command line in the Matomo directory:

`php7.2 ./console googleanalyticsimporter:import-reports -vvv --property=UA-xxxxxx-xx --account=xxxxx --view=xxxxxx --dates=2018-04-14,2020-10-28 --idsite=4`

And after executing I got the following error:

```
ERROR [2020-11-01 10:57:03] 16986  Uncaught exception: /var/www/matomo/plugins/GoogleAnalyticsImporter/ImportStatus.php(176): Import was cancelled.
Import was cancelled.
#0 /var/www/matomo/plugins/GoogleAnalyticsImporter/Commands/ImportReports.php(129): Piwik\Plugins\GoogleAnalyticsImporter\ImportStatus->getImportStatus('4')
#1 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\GoogleAnalyticsImporter\Commands\ImportReports->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\GoogleAnalyticsImporter\Commands\ImportReports), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/matomo/core/Console.php(140): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/matomo/core/Access.php(644): Piwik\Console->Piwik\{closure}()
#7 /var/www/matomo/core/Console.php(141): Piwik\Access::doAsSuperUser(Object(Closure))
#8 /var/www/matomo/core/Console.php(93): Piwik\Console->doRunImpl(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/matomo/console(32): Symfony\Component\Console\Application->run()
#11 {main}
DEBUG [2020-11-01 10:57:03] 16986  Loaded plugins: CorePluginsAdmin, CoreAdminHome, CoreHome, WebsiteMeasurable, IntranetMeasurable, Diagnostics, CoreVisualizations, Proxy, API, Widgetize, Transitions, LanguagesManager, Actions, Dashboard, MultiSites, Referrers, UserLanguage, DevicesDetection, Goals, Ecommerce, SEO, Events, UserCountry, GeoIp2, VisitsSummary, VisitFrequency, VisitTime, VisitorInterest, RssWidget, Feedback, Monolog, Login, TwoFactorAuth, UsersManager, SitesManager, Installation, CoreUpdater, CoreConsole, ScheduledReports, UserCountryMap, Live, CustomVariables, PrivacyManager, ImageGraph, Annotations, MobileMessaging, Overlay, SegmentEditor, Insights, Morpheus, Contents, BulkTracking, Resolution, DevicePlugins, Heartbeat, Intl, Marketplace, ProfessionalServices, UserId, CustomPiwikJs, Tour, Provider, BotTracker, GoogleAnalyticsImporter, QueuedTracking


                         
  [Exception]            
  Import was cancelled.  
                       


Exception trace:
 () at /var/www/matomo/plugins/GoogleAnalyticsImporter/ImportStatus.php:176
 Piwik\Plugins\GoogleAnalyticsImporter\ImportStatus->getImportStatus() at /var/www/matomo/plugins/GoogleAnalyticsImporter/Commands/ImportReports.php:129
 Piwik\Plugins\GoogleAnalyticsImporter\Commands\ImportReports->execute() at /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at n/a:n/a
 call_user_func() at /var/www/matomo/core/Console.php:140
 Piwik\Console->Piwik\{closure}() at /var/www/matomo/core/Access.php:644
 Piwik\Access::doAsSuperUser() at /var/www/matomo/core/Console.php:141
 Piwik\Console->doRunImpl() at /var/www/matomo/core/Console.php:93
 Piwik\Console->doRun() at /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /var/www/matomo/console:32

googleanalyticsimporter:import-reports [--property="..."] [--account="..."] [--view="..."] [--dates="..."] [--idsite="..."] [--cvar-count="..."] [--skip-archiving] [--mobile-app] [--timezone="..."] [--extra-custom-dimension="..."]
```
php 7.2 has this version:

```
PHP 7.2.34-4+0~20201018.51+debian10~1.gbpc553f7 (cli) (built: Oct 18 2020 21:34:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.34-4+0~20201018.51+debian10~1.gbpc553f7, Copyright (c) 1999-2018, by Zend Technologies
```
GoogleAnalyticsImporter is v. **1.5.6.**

I tried it also with php 7.3 and with a standard php.ini. No further error notes in log files.
I tried it with quotes and without. Also for other sites and with different date ranges. Everytime the same error.

Any hint what to do?

**Comment by diosmosis** [comment]
Hi @wcz-txp, if you're using the CLI command to *start* an import, then you shouldn't need the `--idsite` parameter. The command will create a new site. If you want to *resume* an import, then you supply the `--idsite` parameter alone.

Note: if you're trying to import data into an existing matomo site, then that is not currently supported (there is an issue for this already). Unfortunately, in that case the best that can be done is importing into a new site and using RollUpReporting (a premium plugin) to create a roll-up site including both the imported data and the newly tracked data.

**Comment by wcz-txp** [comment]
> Note: if you're trying to import data into an existing matomo site, then that is not currently supported (there is an issue for this already). Unfortunately, in that case the best that can be done is importing into a new site and using RollUpReporting (a premium plugin) to create a roll-up site including both the imported data and the newly tracked data.

Ah, that's the problem. So if I want to switch from Google to Matomo, I have to import the old data first and only after that I can start to measure the traffic with Matomo. Or is it possible to merge data in Matomo?

For example I import Analytics data as "site 1" and the Matomo is already collecting data in "site 2" and after finishing the import I can merge site 1 and site 2, so nothing is lost? I'm asking because importing of old data from the last five years takes several days. And that's only for one site. I have to import data for seven sites.

My idea was to start collecting data with Matomo for these sites already now and programming in parallel these seven import jobs, forget about that for a while and in some weeks after finishing the import, I wanted to switch off Analytics forever.

**Comment by diosmosis** [comment]
> Ah, that's the problem. So if I want to switch from Google to Matomo, I have to import the old data first and only after that I can start to measure the traffic with Matomo. Or is it possible to merge data in Matomo?

The only way to do that currently would be to use https://plugins.matomo.org/RollUpReporting which unfortunately costs money. That said, the only thing having a single site with all the data really does is allow comparison between old dates and new dates (and of course, you'll get accurate data for the year you switched from GA). If this is something you don't need, you could get by w/ just switching between sites (though I suppose it might be inconvenient).

Otherwise, importing and then tracking is also an option, though you should be able to start tracking immediately if you set an appropriate end date. For example, you could:

- get ready to start tracking to matomo on your website (w/o actually tracking)
- then on one day (for the sake of an example, let's just say 11/15/2020), you decide to switch, so you'd start an import w/ no start date (to use the GA property creation date) and an end date of 11/15/2020.
- then, the next day, 11/16/2020, you start tracking on your website to matomo

This way, both data stays on one site. You can also keep tracking to GA until you're sure you don't need to do that, since the import would just stop at 11/15/2020. It's really just a matter of timing.

Another approach is to just start ongoing imports for all your sites, so they will just keep importing data from GA w/ no end date. Then you can just get ready on each site, on your schedule, to track to Matomo, and on the day you decide to start tracking, set the end date for the import job to one day before.

Yet another approach would be to start ongoing imports, then just start tracking while keeping in mind the date you start tracking to Matomo. Then cancel the import, and invalidate the report data for days since you started tracking onwards. This will force a re-computing of them, using the tracked data.

Would any of these work for you?

**Comment by wcz-txp** [comment]
Thank you for this explanation. 
So, if I get it right, than the "problem" is, that Matomo cannot import backward data for a already existing site id, but it is possible to start an import - lets's say from 2015 - and after that one can already start to collect new data on this site, while the import process is filling the gap between the import start data in 2015 and the start data of tracking visits today.
So, I started to import all of my sites and it's actually in process. I plan than to switch the Matomo code to the new site ids at midnight. 
Thank you for helping me to figure that out. It is anyway great to have this possibility of importing old data from Google! I think, that this issue can be now closed.

**Comment by wcz-txp** [comment]
After 18 days these seven sites were successfully imported, while Matomo was in parallel already collecting new data. @diosmosis Thank you for this great plugin!

![изображение](https://user-images.githubusercontent.com/2091265/99785769-46b5c000-2b26-11eb-9324-12c62bfb5d26.png)

**Comment by diosmosis** [comment]
Glad it's working for you @wcz-txp!

**Comment by valerio-bozzolan** [comment]
> Note: if you're trying to import data into an existing matomo site, then that is not currently supported (there is an issue for this already)

~~Uhm. Has anyone been able to find this issue number? (@diosmosis)~~

Here the related issue:

https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/issues/2
