### ISSUE TITLE
Add docs for core:archive cron and for how to debug imports

### ISSUE THREAD

**Issue by dbrgn** [matomo-org/plugin-GoogleAnalyticsImporter#15]
I've set up an import job:

![image](https://user-images.githubusercontent.com/105168/68507054-4e802a80-026b-11ea-88f0-aa489f3e99dd.png)

It worked fine the first day until it ran into the rate limiting. That was expected.

However, that was 3 days ago. Shouldn't the importer have continued on 2019-11-06? Do I need to set up a special cronjob for this task? Is there a way to debug the plugin?

**Comment by diosmosis** [comment]
> Shouldn't the importer have continued on 2019-11-06?

It should continue every day via a scheduled task. Scheduled tasks are usually run through the `core:archive` command when it is setup via cron. If that's not setup via cron, they may be launched during specific tracking requests.

> Do I need to set up a special cronjob for this task?

Ideally you would just need to have the core:archive cron setup. The plugin hasn't been tested w/ scheduled tasks run through the tracker.

> Is there a way to debug the plugin?

The import process logs output to `tmp/logs/`. The file format is `gaimportlog.$idSite.$host.log`. If your import never resumes, however, it points to an issue in the scheduled task.

You can use the https://plugins.matomo.org/TasksTimetable plugin to view scheduled tasks (in the Diagnostic > Scheduled Tasks admin page after installing the plugin). There should be two tasks for the GoogleAnalyticsImporter plugin and it should tell you when the task will run next. (Negative numbers mean it should run the next time scheduled tasks are launched.)

You can try to trigger the task manually by running `./console core:run-scheduled-tasks 'Piwik\Plugins\GoogleAnalyticsImporter\Tasks.resumeScheduledImports'`. This will run the import in the background so you'll have to check the log to see if it actually ran.

Let us know if this doesn't help.

**Comment by dbrgn** [comment]
> Ideally you would just need to have the core:archive cron setup. The plugin hasn't been tested w/ scheduled tasks run through the tracker.

I don't use tracking requests since I rely exclusively on server log analytics.

I only set up cronjobs today. I ran the `core:archive` task manually, but that did not trigger the importer, or at least not directly... Could it be that it doesn't directly trigger the importer, but instead schedules another task that may only run in a few hours? In that case this issue could probably be closed. (Maybe a note about the cronjob could be added to the docs.)

> You can use the https://plugins.matomo.org/TasksTimetable plugin to view scheduled tasks

Thanks, that's useful! The `Piwik\Plugins\GoogleAnalyticsImporter\Tasks.resumeScheduledImports` task is scheduled in a bit more than an hour.

I triggered the task manually using the command you linked above, now the import job is `ongoing` again.

**Comment by diosmosis** [comment]
> Could it be that it doesn't directly trigger the importer, but instead schedules another task that may only run in a few hours? 

Tasks are run at certain times of day, while the core:archive command is meant to be run hourly. So it may not launch every scheduled task each time. If the import command doesn't run automatically the next day, then there's something strange going on.

**Comment by dbrgn** [comment]
Ok, thank you for your help! I'll close this issue for now. If anything can be improved here, then maybe it's the docs, but the jobs do seem to work as intended :slightly_smiling_face:

**Comment by diosmosis** [comment]
Feel free to leave it open, it makes sense to improve the docs 👍

**Comment by diosmosis** [comment]
User docs should be better now, closing.
