### ISSUE TITLE
Importer scheduler not working

### ISSUE THREAD

**Issue by aeneasr** [matomo-org/plugin-GoogleAnalyticsImporter#152]
After setting up OAuth2 and everything, the importer scheduler fails to load:

<img width="1322" alt="Bildschirmfoto 2020-12-05 um 09 45 03" src="https://user-images.githubusercontent.com/3372410/101238157-9b3c6c00-36de-11eb-9066-ce0b3ef05ede.png">

The console shows this error: https://code.angularjs.org/1.8.2/docs/error/$controller/ctrlreg?p0=ImportSchedulerController

I am using matomo 4.0.3 and 4.0.4 (checked both) and 4.0.3 of this plugin.

**Comment by diosmosis** [comment]
@aeneasr can you try the following:

- check to make sure the `plugins/GoogleAnalyticsImporter/angularjs/import-scheduler/import-scheduler.controller.js` is on your server
- check that the file is mentioned in this file: https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/GoogleAnalyticsImporter.php#L142 
- if they both are, try running `php console core:clear-caches` and clear your browser cache

**Comment by aeneasr** [comment]
Thank you! I reinstalled everything and it now works fine :)
