### ISSUE TITLE
Increase timeout when completing OAuth procedure

### ISSUE THREAD

**Issue by Starker3** [matomo-org/plugin-GoogleAnalyticsImporter#161]
When viewing the Google Analytics Importer page for more than 5 minutes, we get a "Form Security Failed" error when clicking on the "Authorize" button
![image](https://user-images.githubusercontent.com/20905821/106821534-356e5f80-66e2-11eb-8da2-4578c83244ca.png)

This can be quite frustrating for people that open the page and don't immediately click on the "Authorize" button after uploading the OAuth Credentials.

Perhaps we can increase the nonce time to a higher value such as 30 minutes?

**Comment by diosmosis** [comment]
Closing for now since this shouldn't happen in 4.1.0, though there appear to be other issues reported in the forum, so might want to hold of on deploying that to cloud for now.

**Comment by Findus23** [comment]
For future reference: The forum thread is https://forum.matomo.org/t/authorisation-of-google-analytics-importer-fail-could-not-verify-the-security-token-on-this-form/40514
