### ISSUE TITLE
[Matomo Cloud] Unable to verify the security token for this form

### ISSUE THREAD

**Issue by Maxtab** [matomo-org/plugin-GoogleAnalyticsImporter#167]
Hi and first, thank you for this tool !

Several weeks ago, I managed to set up the Analytics import successfully. After some time, this one no longer worked (I had launched a large import but which continued normally, day after day).

For more than a month, I have been trying to redo the procedure from scratch to configure the import tool, I followed the tutorial exactly, but at the end, once validated on the Oauth screen, it systematically brings me back to the following URL: 
https://**MYACCOUNT**.matomo.cloud/index.php?module=GoogleAnalyticsImporter&action=processAuthCode&state=35baf077f009fd433144df866e0508c4&code=4/0AY0e-g7-2SZAaXAlh5dTdgeVhqTc7eAOJsQVDqQI1x00LznJWQe88XhNPE3LbQM25ZuQ7g&scope=https://www.googleapis.com/auth/analytics.readonly

With the message "Unable to verify the security token for this form".

I use Matomo Cloud, and I successfully linked my account for the Google Search Console.

Any thoughts ? 

Thank you for your help

![Capture000-matomo](https://user-images.githubusercontent.com/16206268/109404594-e970ac80-7967-11eb-9bdd-8316ec36d518.jpg)

**Comment by diosmosis** [comment]
Hi @Maxtab, this issue is fixed in the latest release of the plugin, however it hasn't yet been deployed on Matomo cloud (it will be deployed with version 4.2.1 in a couple days).

Also, note you can also go through Matomo support instead of github for things like this if you are a cloud user.
