### ISSUE TITLE
Can't add a new import job

### ISSUE THREAD

**Issue by EmbDclic** [matomo-org/plugin-GoogleAnalyticsImporter#185]
Hi,

I've imported 2 sites a few weeks ago and everything went right. From the same Google Analytics account I just tried to import another website but when the form is submitted the page reload but I don’t get any feedback (good or wrong) and the import job is not added.

The only difference I see is that I have installed the latest Matomo update (4.3.0). Is there any know issue or am I doing something wrong? I have tried to re-authorize but it’s the same.

Thanks

**Comment by diosmosis** [comment]
Hi @EmbDclic, I just tried myself and was able to start an import with an issue. Would you be able to provide some screenshots of the import form (with sensitive information changed but the format kept intact, for example, UA-573657-1 changed to UA-555555-5)?

**Comment by tfunq** [comment]
Hi,
I have the same problem. And I can't remove a previously finished job. No feedback given. Page only reloads. I upgraded to Matomo 4.3.0 and GoogleAnalyticsImporter 4.1.5.

**Comment by EmbDclic** [comment]
@diosmosis Thanks for testing. Here is a screenshot of the values I enter in the different fields.
![screenshot-analyticsimporter](https://user-images.githubusercontent.com/23118296/118782715-ae0ebb80-b88e-11eb-8f32-93096fd58834.png)
I’m also on Matomo 4.3.0 and GoogleAnalyticsImporter 4.1.5.

**Comment by nwabeen** [comment]
Hi,
In the www.yourmatomoinstallationpath.tld/config/config.ini.php file, try changing this parameter to this new value :
adapter=MYSQLI

Next, you can try importing the data with the command line :

cd folder/yourmatomoinstallationpath

php ./console googleanalyticsimporter:import-reports --property=YOUR_PROPERTY_ID --view=YOUR_VIEW_ID

Change OUR_PROPERTY_ID and YOUR_VIEW_ID with your real values.

This fix worked for me. After changing this line, Google Analytics data imported successfully into matomo with the command line.

If it still doesn't work try others different configurations explained in [this help page](https://matomo.org/faq/troubleshooting/faq_194/) from the matomo official website.

 **Altough, i still can't import data from the matomo user interface, like you.... I have encountered the exact same problem stated in this current thread. But this method could be a good workaround, before the user interface will be fixed, to work as expected.**

**Comment by diosmosis** [comment]
@EmbDclic @tfunq are either of you able to provide temporary access to your matomo instances for further debugging? If so, can you email dizzy@innocraft.com?

**Comment by EmbDclic** [comment]
@diosmosis I just sent you an email with the access information to our Matomo instance. Thank you.

**Comment by diosmosis** [comment]
Thanks for the assistance @EmbDclic, there is a regression in core causing the requests to fail: https://github.com/matomo-org/matomo/issues/17596

We'll try and fix it soon.

**Comment by diosmosis** [comment]
Hi @EmbDclic and @tfunq I've just released a new version with a fix, can you try using version 4.1.6 of the plugin?

**Comment by tfunq** [comment]
Works perfectly for me. Thanks a lot :)

**Comment by EmbDclic** [comment]
I confirm that the problem is solved with this fix. Thanks a lot!
