### ISSUE TITLE
Argument #1 ($lhs) must be passed by reference, value given

### ISSUE THREAD

**Issue by pioc92** [matomo-org/plugin-GoogleAnalyticsImporter#204]
Hi, on my dashboard of the google analytics importer plugin, i have this error in orange

WARNING: /plugins/GoogleAnalyticsImporter/ImportStatus.php(227): Warning - Piwik\Plugins\GoogleAnalyticsImporter\ImportStatus::Piwik\Plugins\GoogleAnalyticsImporter\{closure}(): Argument #1 ($lhs) must be passed by reference, value given - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: GoogleAnalyticsImporter, Action: index, In CLI mode: false)

i run matomo on php 8, is it the problem?

Import works fine, it's just a warning...

Thanks

**Comment by sgiehl** [comment]
Hi @pioc92 
Thanks for creating this issue. The plugin was developed on PHP 7, but we aim to have it compatible with newer PHP versions as well. Our automated tests for this plugins are currently only running on PHP 7, but we are preparing it to run on PHP 8 as well. Hope we can sort out this issue within that process.

ping @AltamashShaikh

**Comment by AltamashShaikh** [comment]
@pioc92 
It should be fixed in the next release

**Comment by AltamashShaikh** [comment]
@pioc92 
Version 4.18 released.

**Comment by pioc92** [comment]
Thank you i Will try it

Le mar. 9 nov. 2021 à 08:47, AltamashShaikh ***@***.***> a
écrit :
