### ISSUE TITLE
Google Analytics Import issue

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/plugin-GoogleAnalyticsImporter#217]
This error message appeared after the configuration of the Google Analytics Importer plugin within matomo.cloud on December 20/12/2021.
"{ "error_description": "Either access_token, id_token, or token_handle required" }"
"WARNING: /plugins/GoogleAnalyticsImporter/Google/Authorization.php(90): Notice - Undefined index: access_token - Matomo
4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have
been reported already) (Module: GoogleAnalyticsImporter, Action: processAuthCode, In CLI mode: false)"

**Comment by sgiehl** [comment]
Hi @Chardonneaur. Did that happened when trying to authenticate the account or did when trying to start an import?

**Comment by Chardonneaur** [comment]
@sgiehl finally the issue got fixed, sorry for that.
