### ISSUE TITLE
Cannot undo upload of wrong config file

### ISSUE THREAD

**Issue by ja573** [matomo-org/plugin-GoogleAnalyticsImporter#22]
Uploading a wrong config file causes error "Missing client configuration.". There is no way to reupload the configuration file without deleting the option in the database.

**Comment by diosmosis** [comment]
@ja573 there should be a section in the UI for this:

![image](https://user-images.githubusercontent.com/125140/69234258-8f1d5500-0b43-11ea-832b-b8a5abbc5d15.png)
