### ISSUE TITLE
Referrers datas missing before 2020

### ISSUE THREAD

**Issue by Ornitier** [matomo-org/plugin-GoogleAnalyticsImporter#239]
Hello everyone,

I did a large export from GA, from 2014 to 2022, but I see missing data, in particular referrers datas.
See below screen from GA and from Matomo :

GA
![image](https://user-images.githubusercontent.com/4431707/163156777-3f012177-948d-4046-9ecd-429ac5e45473.png)

Matomo
![image](https://user-images.githubusercontent.com/4431707/163156983-5e62c316-ebc2-4d56-bb73-94926f1ffb54.png)

First data found is January 17th, 2020. Can not understand why.
Tried to dig into the GA query, the response seems... empty.

Did someone got something similar?

**Comment by PrimeranoC** [comment]
Hi, 

I have the same issues. My import is still ongoing, but for the period already archived the referral data ara missing. 
Is it possible to fix this issue?

**Comment by AltamashShaikh** [comment]
Please check this [doc](https://support.google.com/analytics/answer/7667196?hl=en). It can be a issue due to your data retention probably.

**Comment by Ornitier** [comment]
Hi @PrimeranoC and @AltamashShaikh 

I forgot to give news on this case.

Had a little chat with the GA Reporting Google team, it was "normal" that API do not return data for this period because of the data retention that AltamashShaikh mentionned.
But, they could not answer me why I continue to see them into GA views, which was incoherent.

As for me, I have found a way to extract data from browser, and re-inject them in Matomo.

**Comment by PrimeranoC** [comment]
Hi @Ornitier and @AltamashShaikh ,

I also don't understand why then it is possible to see that data on GA, if it should have been deleted. I have the same problem also for the data of the visits from social networks.

@Ornitier I would be interested in the method you found to extract data from browser, and re-inject them in Matomo.
is it a replicable method? does it require advanced skills?

Thank you

**Comment by Ornitier** [comment]
This is the question I asked them. But as Reporting team and "View" team is not the same, they could not answer this...

For the extraction, it's a bit hard.
On GA side, I used the Export button with CSV. You have to do it for **every day** you want to "recover".
Then, I made a plugin, that read all the CSV en push them into Matomo database.

I can't give you the scripts I used, as they are very specific. But it takes me a day for the Matomo dev. I had a JS script for the GA Extract, which launch all the download per day; this might take hours depending on the period you want.

**Comment by PrimeranoC** [comment]
Thank you for the tips, but I think it is a bit too complex, I think I will give up for now. Later I will see if it is necessary to do it or not.

Thanks again

**Comment by AltamashShaikh** [comment]
@PrimeranoC You can check the API response by visiting this URL - https://ga-dev-tools.web.app/query-explorer/
And can select following metrics and dimensions along with the date range where referrer is missing.
![Screenshot from 2022-07-29 08-00-18](https://user-images.githubusercontent.com/14902277/181670488-7bf942f2-f376-42bb-a0f0-ad66904c88bb.png)

I can see for older dates the API returns empty response, whereas for recent ones we are getting the data.
We query the GA Reporting API to fetch the data and can't do much if the API doesn't return the data for that period.

Also is there anything we can help you?  

@Ornitier can we close this issue ?

**Comment by Ornitier** [comment]
Yes ! Thank you for your feedback.

**Comment by xabaras73** [comment]
Let me disagree

I have a 26 month data retention

In fact I don't care about old date referer sites. But it's not a API problem

1) with data study (which is based on bees) the data are there
2) using https://ga-dev-tools.web.app/query-explorer/ on dates longer than 26 months the referer data is listed

![image](https://user-images.githubusercontent.com/112861851/188573702-7c72da1e-3fe5-480b-bf26-e99e4ac456f0.png)

**Comment by xabaras73** [comment]
Finally discovered the problem

You see
https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/issues/265
