### ISSUE TITLE
Difference between Matomo API cals number and Google.

### ISSUE THREAD

**Issue by petrillek** [matomo-org/plugin-GoogleAnalyticsImporter#243]
Hello,
new Matomo user here.

I've a couple of sites running on GA for 10+ years. I would like to migrate them to Matomo for various reasons.
It imported about 5 months of data from one of the site and stopped with status: **rate_limited**. If I look in the Google console I can see the API usage is only about 20% (~10.000 api calls out of 50.000). 
I know it will take days to import all of these old data, but still I do want to use as much of the limit as possible.

**Comment by AltamashShaikh** [comment]
@petrillek I hope this explains your concern.
![image](https://user-images.githubusercontent.com/14902277/167057758-8d5c05c0-3108-4de9-b661-7b1d34313848.png)
