### ISSUE TITLE
Authorization process broken without error

### ISSUE THREAD

**Issue by Tybaze** [matomo-org/plugin-GoogleAnalyticsImporter#246]
Dear Matomo team, 

I have found an unwanted behavior that make me spend 1 hour to find the issue about the "redirect_uri" of the OAuth process.
Dear Matomo team, 

I have found an unwanted behavior that make me spend 1 hour to find the issue about the "redirect_uri" of the OAuth process.

I should do a PR but I'm not fluent with your coding process.

Let me explain the problem, in the Google Authorization library :
[./Google/Authorization.php](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.2.0/Google/Authorization.php#L122)
Line 122 you load the configuration

_Which is init here : 
[./config/config.php](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.2.0/config/config.php#L32)
And here you set the redirectUri with arguments : "?module=GoogleAnalyticsImporter&action=processAuthCode"
$googleClient->setRedirectUri($redirectUrl);_

But Line Authorization.php:123: you call : 
$this->configureClient($client);
And this method overwrite the configuration , but this time from Google uploaded JSON file.

But this json from Google may also contain a "redirect_uris" attribute, that have been defined, in my bad case to multiple values during key generation - I have fixed it in the Google console, but I do not update the json file.

It will result in a broken authorization process, without any error displayed and redirecting to the home page or 404 value.

Once parsed the json value redirect_uris will use the first value as "redirect_uri", this is due to google api client
[Client.php](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/5f7effbc1bb31b911fb3cc54a75920d507222219/vendor/google/apiclient/src/Client.php#L985)

**Fix proposal :** 
The configureClient() method should apply the json from google, excepted for the attribute "request_uris", which must be the one defined by the plugin, and not by google configuration.

A simple : 
unset($clientConfig['web']['redirect_uris']);
Should do the job just before the setAuthConfig here : [Authorization:98](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.2.0/Google/Authorization.php#L98)

In that case, if any a bad redirect_uri or serveral URI are configured into Google console, Google Auth page will display, "wrong uri please add ?module ..." which can be easily fix, without reimporting the configuration.

**Comment by AltamashShaikh** [comment]
@Tybaze we wouldn't want to change any existing config generated by Google. This looks more like a issue while configuring OAuth keys, which can be fixed easily there.

**Comment by AltamashShaikh** [comment]
Closing this for now, if more people report this similar issue we can think of adding a fix for it

**Comment by Tybaze** [comment]
Another solution, really more accurate than my previous fast bug fix :
First you load the Google Json conf
Then you apply Matomo configuration to overwrite the wanted value.

But a configuration setter need to be added to apply the redirectUri

There will be probaly not any other report of this bug, because it takes me more than one hour dig into the code to diagnose it, and standard user will tell "GA importing not working, feature is broken, redirecting me to a 404 or homepage" 


More of that it's also a security issue.
With a few social engineering you tell to the GAuth Keyowner to add your "bad intentionned url" return first, then the valid one
Then Matomo will redirect to the bad injected URL without any check, which will leak the token to the attacker.

Or even badder, if a user follow exactly the demo :
https://matomo.org/guide/installation-maintenance/import-google-analytics/
Pause at 3:00.
If a customer enter the same URL in Google Console, he will be really redirected to "example.matomo.cloud"
Which means that Matomo servers will received customer Google OAuth token for on premise install.

You shouldn't let any external service decide where your Backoffice redirected an Admin User.

**Comment by AltamashShaikh** [comment]
@Tybaze We understand your concern, we can try to validate the domain in such case.
I will try to find sometime to do so in coming weeks.

**Comment by AltamashShaikh** [comment]
@Tybaze FYI created this PR - https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/pull/255 to solve such issues

**Comment by Tybaze** [comment]
Thank you very much ! 
I have tested the PR with an multi-url starting with a wrong one, and it's worked.
