### ISSUE TITLE
Import deprecated app properties

### ISSUE THREAD

**Issue by jphorn** [matomo-org/plugin-GoogleAnalyticsImporter#25]
As you've might have read Google has [sunsetted the Google Analytics Services SDK](https://support.google.com/firebase/answer/9167112?ref_topic=6386699), which was in use by many (older) (iOS) apps. We have used this SDK from March 2013 until its sunset data October, 31st 2019.
I'm looking to back-up/import this historical data in my Matomo instance, but the GoogleAnalyticsImporter plugin is expecting URL values:

> Error
> URLs: You must specify at least one URL for the website.

Are you looking into supporting (old) GA app properties as well? All the reported data will be completely deleted by Google in February 2020.

> After our service is fully turned down in February 2020, these legacy properties will no longer be accessible via the Google Analytics UI or API, and the associated data will be deleted from Google Analytics servers. In advance of this turndown, we recommend that you export the data so you can retrieve it later. 

Their export function is very limited (as you might be well aware) and you have to manually export every single report view. This is almost undoable, so here's hoping the Matomo GA Importer will be able to fill this void (and it'll be available before the final purge...)

_Full email below_

> **As of October 31, 2019, we have stopped processing data from your Google Analytics account(s)** <name> (XXXXXX) for the properties listed below that are using the older style of Google Analytics mobile apps reporting and the legacy Google Analytics Services SDK.
> 
> You will continue to have reporting access until January 31, 2020, after which your property and its data will be permanently deleted. See below for the remaining decommissioning timeline.
> --
> Which of my properties are affected?
> Affected Properties: All apps (UA-XXXXXX-XX), XXXXXX App (UA-XXXXXX-XX).
> 
> What does “stopped processing” mean?
> New data you send to the Google Analytics properties listed above will not be serviced and will therefore, not appear on your reports. This will appear as though you are no longer sending app data to Google Analytics.
> 
> What will happen to my Google Analytics properties listed above?
> • Reporting access through our UI and API access will remain available for these properties’ historical data until January 31, 2020.
> • After our service is fully turned down in February 2020, these legacy properties will no longer be accessible via our Google Analytics UI or API, and the associated data will be deleted from Google Analytics servers. In advance of this turndown, we recommend that you retrieve this historical data through report exports. 
>

**Comment by diosmosis** [comment]
@jphorn the property you're trying to import doesn't have a URL (because it's an app), correct?

**Comment by jphorn** [comment]
Correct. It's a property for an iOS app.

**Comment by diosmosis** [comment]
This might be an easy fix, I'll see if I can put up a PR for testing.

**Comment by jphorn** [comment]
It'd be happy to add you or someone else to this property with Read and Analyze capability if necessary for testing.

**Comment by diosmosis** [comment]
@jphorn could you try testing with this PR: https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/pull/26 ? Right now I've only modified the CLI command for importing. If it works for you for a small date range, I'll add the ability to specify the property is a mobile app in the UI. If it doesn't work, then that likely means the import data is different for mobile app properties, and I would need access to make it work fully (email support@matomo.org in that case).

You'll have to enable the MobileAppMeasurable plugin before running, and possibly disable TagManager (it seemed to have trouble with Mobile app types for me; if a bug it would have to be fixed in core).

**Comment by diosmosis** [comment]
@jphorn Were you able to test the updated code? Do you need any help? Let us know if it's not possible for you to test it.

**Comment by jphorn** [comment]
Hi @diosmosis. Apologies for not replying sooner. Alas I'm unable to test your PR myself, since my Matomo self hosted instance was installed for me and I'm not sure how to deploy the PR. I have added support@matomo.org to the specific view though so you're able to test with my data. Would that be sufficient?

**Comment by diosmosis** [comment]
@jphorn I emailed you at your iculture.nl address w/ a google email you should be able to use.

**Comment by diosmosis** [comment]
This is working on master, closing.
