### ISSUE TITLE
Add required date format to the date field settings' help text

### ISSUE THREAD

**Issue by varunKothare** [matomo-org/plugin-GoogleAnalyticsImporter#261]
Administration->System->Analytics Importer

start-date

end-date

It would be good to identify the format of the date

**Comment by AltamashShaikh** [comment]
Something like this will be helpful @varunKothare ?
![Screenshot from 2022-08-01 09-24-10](https://user-images.githubusercontent.com/14902277/182069127-cf69460e-d1d5-4b04-919d-27b2a91db9c0.png)

**Comment by varunKothare** [comment]
@AltamashShaikh Yes please.

**Comment by AltamashShaikh** [comment]
Seems we already implemented this and forgot to close this issue

![Screenshot from 2024-05-30 09-12-19](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/assets/14902277/183f9ee8-2eb2-4495-9b34-acb9d4608945)
