### ISSUE TITLE
Google Workspace account

### ISSUE THREAD

**Issue by miiimooo** [matomo-org/plugin-GoogleAnalyticsImporter#262]
The documentation specifies that with an internal Google cloud app and a Google Workspace account it is not necessary to re-authorize the importer every day, and also there should be no daily limits in the Google API.

I cannot confirm this: I have set up the cloud app from my workspace account, it's internal but still I need to re-authorize the app every day. 

Can you confirm this works, is there someone at Google to ping or should this be removed from the docs maybe? 

My import has been growing in terms of days remaining. It wen from 24 days, to 160 days and now over 280 days

**Comment by snake14** [comment]
@miiimooo Thank you for creating this issue. I'm sorry to hear that you are experiencing difficulties. I believe that the [FAQ describing authorising](https://matomo.org/faq/general/set-up-google-analytics-import/#2-creating-google-oauth-client-config) was recently updated to show the necessary steps to avoid having to re-authorise. I think the key steps are 13-15, where you skip adding scopes and test users and then publish. @AltamashShaikh Do you have any other recommendations?

**Comment by AltamashShaikh** [comment]
@miiimooo Is your APP "internal" or "external" ?
If its "external" can you check if you have added any scopes ?
If yes remove that and publish your App and re-authorise and post that the re-authorisation after 7 days should go away.

We recently update the "setup guide", so please do have a look at the [FAQ](https://matomo.org/faq/general/set-up-google-analytics-import/#2-creating-google-oauth-client-config) too.

**Comment by miiimooo** [comment]
@snake14 @AltamashShaikh thanks for getting back to me. I have set the app to User type: internal.

At the bottom of the summary page it says:
![image](https://user-images.githubusercontent.com/1226434/186365922-571d5638-1ed5-45c8-a6c6-8af467c8a85f.png)

Do you mean I should remove this Scope, and then re-authorize?

At the moment, the GA importer gets killed after a while. Here a screenshot showing the Google API rates. I notice there a high error rate :fearful: (7 days scale)
![image](https://user-images.githubusercontent.com/1226434/186366323-48c45519-483f-4557-80a3-f3a00a716ec0.png)
![image](https://user-images.githubusercontent.com/1226434/186366387-a03f3c54-32af-49a9-8d77-f8b94ee22802.png)

**Comment by AltamashShaikh** [comment]
@miiimooo Was it "Internal" from start ? Or did you just updated to "Internal". If yes just reauthorise, resume the import by clicking the play button and check again.

Also for internal accounts scope addition is really optional and not needed so you can keep or delete it anything would do.

**Comment by snake14** [comment]
@miiimooo Since it's been a while without hearing back, I'm going to go ahead and close this issue. If you have any further questions or feel that this issue needs to be reopened, please let us know.
