### ISSUE TITLE
Import google analytics bug

### ISSUE THREAD

**Issue by xabaras73** [matomo-org/plugin-GoogleAnalyticsImporter#265]
I did several tests on importing google analytics data
I encountered two problems:

Minor: the data imported prior to July 2012 are missing the entry page, exit page and other reports.
More serious: Referer site data for periods older than 2 years is not imported
The data on the google analytics reports are there and trying to access via Data Studio (therefore via API) there are equally

It seems that matomo imports the data but signals an incompatibility

**Comment by snake14** [comment]
Hi @xabaras73 . Thank you for taking the time to create this issue. It does sound like a compatibility issue, but I'm not familiar enough with it to know for sure. Can you provide any insights @AltamashShaikh ?

**Comment by AltamashShaikh** [comment]
@xabaras73 Can you check this [issue](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/issues/239) 
The difference is due to API not returning data for older dates.

**Comment by xabaras73** [comment]
Let me disagree

I have a 26 month data retention

In fact I don't care about old date referer sites. But it's not a API problem

1) with data study (which is based on bees) the data are there
2) using https://ga-dev-tools.web.app/query-explorer/ on dates longer than 26 months the referer data is listed

![image](https://user-images.githubusercontent.com/112861851/188573702-7c72da1e-3fe5-480b-bf26-e99e4ac456f0.png)

**Comment by AltamashShaikh** [comment]
@xabaras73 
Did you try with the following combination ?
![Screenshot from 2022-07-29 08-00-18](https://user-images.githubusercontent.com/14902277/181670488-7bf942f2-f376-42bb-a0f0-ad66904c88bb.png)

How many results is the API returning ? If yes can you schedule a new Import by enabling verbose and share the log file 
The path to your log file will be `/your/path/to/your/matomo/tmp/logs/gaimportlog.{siteIDCreatedForImport}..log`

**Comment by martinomh** [comment]
The problem lies when the API request contains ga:users metric.

That's a metric that's unavailable for periods exceeding the data retention.

When queried, GA APIs give an empty response.

The Matomo plugin apparently doesn't query ga:users in every API request... and that's the reason why you're seeing partial data instead of no data.

I humbly suggest to add an option to NOT import Users data to the Google Analytics importer plugin (therefore only importing sessions metrics).

Or, even better: a setting for specifying the Data Retention limit on GA... that makes the plugin stop querying ga:users before that.

**Comment by xabaras73** [comment]
> 
We finally figured out where the problem is
I also hope the plugin can be updated to use ga: session beyond the retention date

**Comment by AltamashShaikh** [comment]
@xabaras73 that wont be a easy fix I assume but if you can send the PR for the same will be happy to merge it

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/import-google-analytics-bug/47230/2

**Comment by AltamashShaikh** [comment]
@xabaras73 We already have this in place - https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Google/GoogleAnalyticsQueryService.php#L27 and https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Google/GoogleAnalyticsQueryService.php#L108
