### ISSUE TITLE
Problems with the recent change "import recent dates first"

### ISSUE THREAD

**Issue by MarcoPNS** [matomo-org/plugin-GoogleAnalyticsImporter#272]
I already pointed out in the PR #245  that there is a problem with bigger GA Properties and the recent change "import recent dates first". The import switch to soon to a finished state that I can't import any bigger GA Property. 

There are already some logs from me in the PR. Unfortunately there is not much to see in the logs. My guess is (since the "Last imported day" is also not updated correctly) that there are checks in the code that continue to assume the previous direction and therefore switch to finished at an error / quota limit because the last day (which is the first day that got imported) has already been imported. 

I have now reversed the function in my code so that the oldest day is imported first. After that everything works again.

**Comment by snake14** [comment]
Hi @MarcoPNS . Thank you for taking the time to create this issue and provide more information. I'm sorry to hear about the problems you've been experiencing. @AltamashShaikh do you have any insights or suggestions?

**Comment by AltamashShaikh** [comment]
@MarcoPNS Can you check if #273 works as expected ?

**Comment by AltamashShaikh** [comment]
@MarcoPNS Updating `ImportStatus.php` file on your instance with this [file](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/7d63d512c9a2b530d2980e9d218d1bbfc0353fcd/ImportStatus.php) should be sufficient

**Comment by Starker3** [comment]
@AltamashShaikh An issue very similar to this was reported in the forum for the 4.3.3 version where this should be fixed: https://forum.matomo.org/t/google-analytics-import-process-gets-killed-after-1-day/47546

What they're seeing there is that the import starts on the most recent date and goes backwards as expected, but after the quota is reached for that day it doesn't continue the next day.

**Comment by AltamashShaikh** [comment]
@Starker3 will check this and update you here

**Comment by AltamashShaikh** [comment]
@Starker3 - created https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/pull/281

**Comment by PrimeranoC** [comment]
@AltamashShaikh 
 have the same problem and can't solve it.
I tried to restart the import by setting a different date range, but it continues to stop due to the limit reached and does not restart the next day. Furthermore, I believe that in redoing the import they are also changing the imported data compared to the previous import.
Do you have any practical suggestions to solve the problem?

**Comment by AltamashShaikh** [comment]
@PrimeranoC can you apply #281 and check if it solves the issue for you ?

It just helped someone, refer - https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/issues/274#issuecomment-1260565371

**Comment by PrimeranoC** [comment]
@AltamashShaikh 
I am using the cloud version and I am not an IT.
I would expect your plugin to work properly without having to put my hands in the code. Do you plan to solve the problem for all users?

**Comment by AltamashShaikh** [comment]
@PrimeranoC For cloud you don't have to update anything, the fix will be applied for all the users but before we release a new version we have to be sure that it doesn't regress further and hence checking with user who reported this, whether applying current patch will fix the issue or not.

**Comment by dhensch** [comment]
Hi @AltamashShaikh , I understand how busy everyone is... Do you have a relative update on how long it will be until the GA Import Issue will be resolved for cloud users? I have some client timelines that I would like to meet, and I just want to understand the magnitude of the issue :) thank you

**Comment by AltamashShaikh** [comment]
Hey @dhensch The new version of the plugin should be live by early next week.
Will update here once I have a better ETA

**Comment by dhensch** [comment]
@AltamashShaikh  I really appreciate your prompt response, it means a lot. Good Luck!

**Comment by AltamashShaikh** [comment]
@PrimeranoC  @dhensch The new version of the plugin was released on cloud today

**Comment by PrimeranoC** [comment]
Hi @AltamashShaikh 
Thanks for the update. The import seems to have started working correctly again.
Thanks so much for the support.
