### ISSUE TITLE
Upgrade to latest, can't see config anymore

### ISSUE THREAD

**Issue by valentin-ed** [matomo-org/plugin-GoogleAnalyticsImporter#278]
Hi team,

After upgrade to the latest (Matomo and plugins) i can't see anymore the configuration that have been done previously. The data seems to be still in database but i cant' see it in my admin dashboard.

![2022-09-23_16-54](https://user-images.githubusercontent.com/73354059/191989960-2aaa83cc-c2a8-48ae-9a32-c1650f662ced.png)
![2022-09-23_16-53](https://user-images.githubusercontent.com/73354059/191989982-b410a89b-131f-4f51-a741-c5c40c097f10.png)

What should i do to make sure everything still working ?

**Comment by AltamashShaikh** [comment]
@valentin-ed I tried checking what could go wrong and the only possible thing is the `GoogleAnalyticsImporter.clientConfiguration` value is not a proper JSON. I tried updating mine to a invalid JSON at last and can see the same.
![Screenshot from 2022-09-26 08-08-00](https://user-images.githubusercontent.com/14902277/192183291-a257639c-d95e-484a-8d81-e8815e879fd4.png)


To confirm that's the case can you copy the value from DB and validate the JSON using something [like this](https://jsonlint.com/)?

**Comment by valentin-ed** [comment]
How it could be possibly be wrong ? I mean, from the previous version was working well. 
The field was "cleaned up" and i manage to find a "workaround" by restoring only field in `matomo_option` with "GoogleAnalytics" in the name. 

We can close if you want but maybe some user may have the same issue !

**Comment by AltamashShaikh** [comment]
@valentin-ed closing for now, we can open this again if others face same issue.
