### ISSUE TITLE
Display a message about new site creation during import

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/plugin-GoogleAnalyticsImporter#282]
While configuring the import, it would be helpful to display a message in a popup or  banner with a message about the new site creation.

Example:
A new website will be created and all the data will be imported in the site created. Data can not be imported in an existing site.

This is a long message, but it is the crux.

**Comment by AltamashShaikh** [comment]
Hey @KarthikRaja1388 Its already there
![Screenshot from 2022-09-29 12-22-20](https://user-images.githubusercontent.com/14902277/192960068-54eeaa6f-2359-4dc6-8867-ab68b89a2d69.png)

**Comment by KarthikRaja1388** [comment]
@AltamashShaikh Thanks I did not realize it
