### ISSUE TITLE
Date Format example not shown in several places

### ISSUE THREAD

**Issue by Starker3** [matomo-org/plugin-GoogleAnalyticsImporter#286]
There are several places where a date can be input but no date format example is given. 

For example for the GA3 import:
![image](https://user-images.githubusercontent.com/20905821/194943801-d3b517e2-bcda-46ea-9051-cfff909ed274.png)

GA4 import:
![image](https://user-images.githubusercontent.com/20905821/194943827-b8d0f85e-70b7-4f40-8ce5-87999299f9d4.png)

When clicking "Change Import End Date":
![image](https://user-images.githubusercontent.com/20905821/194943883-6c2b438d-66d8-4649-b6c3-8542d6bc9900.png)

This means that users would need to guess the format and if they get it wrong they would need to check the error message to find out the date format:
![image](https://user-images.githubusercontent.com/20905821/194944266-8109436e-fe5d-4e8c-b11c-243330d8e92e.png)

The date format example is however shown when clicking "Re-import Date Range" for example:
![image](https://user-images.githubusercontent.com/20905821/194943977-7607401c-c76a-446f-be29-a692b12689bb.png)

**Comment by snake14** [comment]
@Starker3 Thank you for your suggestion. The next release of this plugin should include more hints next to form inputs to make the date format easier to remember.
