### ISSUE TITLE
"invalid client configuration" with OAuth JSON for GA Importer

### ISSUE THREAD

**Issue by cspenn** [matomo-org/plugin-GoogleAnalyticsImporter#296]
I'm attempting to load a JSON file with my OAuth credentials for the Google Analytics importer and receive the same generic error message:

"Missing or invalid client configuration, please reupload."

I have confirmed the service account is enabled for OAuth on the Google side, the account has rights to the Analytics API, and billing is active. This account works with other OAuth implementations.

Here's the contents of the JSON, redacted:

```
{"l$b":{"client_id":"thecorrectid.apps.googleusercontent.com","project_id":"mygcpproject","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"myclientsecret","redirect_uris":["http://mywebsite/index.php?module=GoogleAnalyticsImporter&action=processAuthCode"],"javascript_origins":["http://mywebsite"]}}
```

## Your Environment

* Matomo Version:  4.12.3
* PHP Version: 8.1.2
* Server Operating System: Ubuntu 22.04 LTS
* Additionally installed plugins: Google Analytics Importer

**Comment by peterhashair** [comment]
@AltamashShaikh any idea on that one?

**Comment by AltamashShaikh** [comment]
@cspenn You are using a service account config and Matomo GA Importer requires an Oauth config to import your GA Data.
You can check this [guide](https://matomo.org/faq/general/set-up-google-analytics-import/) to setup an OAuth credentials and try with that.

**Comment by AltamashShaikh** [comment]
@cspenn Just FYI the valid JSON looks something like this
```
{"web":{"client_id":"xxxx","project_id":"{project_name}","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"xxx","redirect_uris":["https://{DOMAIN_NAME}/index.php?module=GoogleAnalyticsImporter&action=processAuthCode"],"javascript_origins":["https://{DOMAIN_NAME}"]}}
```

**Comment by cspenn** [comment]
Thanks @AltamashShaikh - I followed those steps and ended up with a "Could not verify the security token on this form." after doing the OAuth authorization.

**Comment by snake14** [comment]
Hi @cspenn . Please try refreshing the page and then authorising again. You usually get a security token error if you've been on the page too long before authorising.

**Comment by cspenn** [comment]
@snake14 Thanks - I refreshed, removed the previous JSON authorization, and tried again from scratch - still no luck. This is what comes back in the URL:

http://mywebsite/index.php?module=GoogleAnalyticsImporter&action=processAuthCode&state=7989ca4479e7a582853b8472825ea51a&code=4/0AfgeXvt2EDH3QJfOTPKP8sL-n5Pme8JIYtob_4lab2Vier4JFwe6mtVZB-DAW0BEqqPthA&scope=https://www.googleapis.com/auth/analytics.readonly

**Comment by snake14** [comment]
@cspenn That looks like the correct URL as long as the protocol and domain match your Matomo server. Is your Matomo server using `HTTP` and not `HTTPS`? If it's using `HTTPS` you'll need to update your config and upload it again.

**Comment by AltamashShaikh** [comment]
@cspenn Is your webserver blocking this request by any chance ?

**Comment by cspenn** [comment]
@snake14  @AltamashShaikh It shouldn't be - I have ufw open for incoming on 80 and 443, and it definitely accepts incoming for both, but I'm using HTTP

**Comment by AltamashShaikh** [comment]
@cspenn The URL you shared comes after authorization right ?
The behaviour is 
Click on Matomo Instance for Authorization -> Request to Google -> Redirects back to Matomo with the above URL
The redirect URL completes the authorization, do you see a blank page when it redirects back ?
If yes can you check is the URL correctly reaches your webserver, for example we have seen in past that apache was blocking the request due to 'user.profile` for other plugin.
Can you check same applies to you

Also if you see any error in Matomo can you provide a screenshot of the error too ?

**Comment by cspenn** [comment]
@AltamashShaikh Correct. The URL comes after authorization. I load the JSON file, click for the authorization, the browser window goes to Google, I authenticate, and it comes back to the error page - not a blank page. I'll upload a screenshot shortly.

**Comment by cspenn** [comment]
![Untitled](https://user-images.githubusercontent.com/6747905/202772121-360af873-da64-48f9-a794-634131d23c6f.gif)

**Comment by cspenn** [comment]
This is what was in my matomo error log:

[Fri Nov 18 17:58:23.728251 2022] [php:notice] [pid 760605] [client 199.36.244.24:56422] [myserverip] Error in Matomo: Invalid redirect_uris, atleast 1 uri should match the uri &quot;http://myserverip/in>

**Comment by AltamashShaikh** [comment]
@cspenn can you share the content of your file by removing the sensitive data?

Something like this
```
{"web":{"client_id":"xxxx","project_id":"{project_name}","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"xxx","redirect_uris":["https://{DOMAIN_NAME}/index.php?module=GoogleAnalyticsImporter&action=processAuthCode"],"javascript_origins":["https://{DOMAIN_NAME}"]}}
```
Also will it be possible to share the URL where you upload this file?

It will be easy for us to compare and find the issue
