### ISSUE TITLE
Error during import

### ISSUE THREAD

**Issue by denarie** [matomo-org/plugin-GoogleAnalyticsImporter#32]
Just started a new import from Google Analytics and got the following error message:
`Error message: Error on day 2017-03-20, { "error": { "code": 400, "message": "Unknown metric(s): ga:totalValue, ga:transactions\nFor details see https://developers.google.com/analytics/devguides/reporting/core/dimsmets.", "errors": [ { "message": "Unknown metric(s): ga:totalValue, ga:transactions\nFor details see https://developers.google.com/analytics/devguides/reporting/core/dimsmets.", "domain": "global", "reason": "badRequest" } ], "status": "INVALID_ARGUMENT" } } 
`

**Comment by diosmosis** [comment]
That's an odd error, given both of those metrics are listed in the link in the error message (https://developers.google.com/analytics/devguides/reporting/core/dimsmets). Is there anything special about your property? Do you have ecommerce disabled for the view you are trying to import?

**Comment by denarie** [comment]
Thank you for your advice: I opened the view in Google Analytics, then enabled ecommerce, saved it, disabled it, saved it again. Then I started the import again. Now it is still running! I think that did the trick!

**Comment by diosmosis** [comment]
I'm glad it's working, though I can't explain why :). I'm going to close this issue, feel free to re-open it if it starts failing again.
