### ISSUE TITLE
Typo in German  Language File

### ISSUE THREAD

**Issue by Tinendo** [matomo-org/plugin-GoogleAnalyticsImporter#323]
Line 89 in de.json reads „Fortfachen. …“, should be „Fortfahren. …“. 

Btw: is there a better way to report and/or correct errors in Language files?

**Comment by AltamashShaikh** [comment]
@Tinendo You can send a PR(pull request), with the change and we can review and merge it accordingly

**Comment by Tinendo** [comment]
@AltamashShaikh Thanks!

**Comment by AltamashShaikh** [comment]
@Tinendo Thanks for the PR I have merged your changes and will release a new version in couple of weeks as per our release cycle.

**Comment by Tinendo** [comment]
@AltamashShaikh Great!
