### ISSUE TITLE
Import cut off after 1000 URLs per day

### ISSUE THREAD

**Issue by miiimooo** [matomo-org/plugin-GoogleAnalyticsImporter#327]
I've run the GA importer for the month of January 2021 for a busier site. When I filter Pageviews in GA (Behaviour > Site Content > All Pages Filter containing "/news/") I get a result set of more than 62000 rows.
The same month in Matomo after a fresh import to a new site ID (Behaviour > Pages) filtered by "/news/" I get a result set with 1655 (same as a previous import to a different site ID).

I wonder whether there is an explanation why more than 60k rows could be missing. Comparing the result sets, I am not sure exactly what to look out for. It looks like the first 500 are similar - though slightly different (especially, it's surprising that the Pageviews and Unique Pageviews in Matomo are lower).
After the first 500 entries the rows look very different. On the last rows the Pageviews is still 20. It looks like it stopped or removed any further rows, in GA there are many Pages with less than 20 Pageviews.

The Import status is "finished". I have run this import twice into fresh Matomo sites and the result is exactly the same

Let me know if there is anything else I can provide to help explain this. I have opened another issue here yesterday that isn't related to this as far as I can see

**Comment by snake14** [comment]
Hi @miiimooo . Thank you for reaching out. Have you tried [triggering an import from the command line](https://matomo.org/faq/general/running-the-google-analytics-import/#setup-an-import-using-the-command-line-for-universal-analytics-ga3)? You might try that and see if any warnings/errors display. If you don't see anything that way, you can include the `-vvv` option to make it run in verbose mode.

**Comment by AltamashShaikh** [comment]
@miiimooo Can you check what counts do you get by visiting this [tool](https://ga-dev-tools.web.app/query-explorer/)

![Screenshot from 2023-01-12 07-41-17](https://user-images.githubusercontent.com/14902277/211959432-cb9afdbf-011b-4a32-abf7-26158dcbf716.png) for the metrics and dimension combination as mentioned in the screenshot ?

**Comment by miiimooo** [comment]
@AltamashShaikh I get "Showing 1000 out of 82181 total results." - so the row count looks more like it should. The equivalent in GA says 110k rows

Talking to our Matomo supplier we think it could be some environment variable that limits the number of URLs.

**Comment by mikkeschiren** [comment]
Supplier here :)  - it seems make no difference in with changing, these values to extreme:

```
        datatable_archiving_maximum_rows_referrers: 500000
        datatable_archiving_maximum_rows_subtable_referrers: 500000
        datatable_archiving_maximum_rows_actions: 500000
        datatable_archiving_maximum_rows_subtable_actions: 500000
        datatable_archiving_maximum_rows_events: 100000
        datatable_archiving_maximum_rows_subtable_events: 100000
        datatable_archiving_maximum_rows_custom_variables: 500000
        datatable_archiving_maximum_rows_subtable_custom_variables: 500000
        datatable_archiving_maximum_rows_site_search: 500000
```

**Comment by mikkeschiren** [comment]
And no special logs in the console pointing on why we get this limit in number of Urls imported.

**Comment by miiimooo** [comment]
Looking through the imported data I noticed that there is no day that has more than 1000 rows by Page URLs in the Pageviews.
I think there must be a limit either in what comes from Google (or is that unlikely because the UA Query Explorer returned considerably more rows) or, I think it's more likely that there is a 1000 limit in the Importer

**Comment by mikkeschiren** [comment]
So the question is - is there any other config that needs change than the one I posted above?

**Comment by AltamashShaikh** [comment]
> datatable_archiving_maximum_rows_subtable_actions

@mikkeschiren Did you retry the import after changing this config values ?

**Comment by miiimooo** [comment]
> @miiimooo Can you check what counts do you get by visiting this [tool](https://ga-dev-tools.web.app/query-explorer/)
> 
> ![Screenshot from 2023-01-12 07-41-17](https://user-images.githubusercontent.com/14902277/211959432-cb9afdbf-011b-4a32-abf7-26158dcbf716.png) for the metrics and dimension combination as mentioned in the screenshot ?

@AltamashShaikh looking at the request that is made there I notice:

![image](https://user-images.githubusercontent.com/1226434/212073732-cf0c1ee6-60f1-480a-ae0d-a674180e6b66.png)

Could it be that the Importer doesn't have paging support and stops after the `max-results=1000` instead of making another request with `start-index=1001`?

**Comment by mikkeschiren** [comment]
> > datatable_archiving_maximum_rows_subtable_actions
> 
> @mikkeschiren Did you retry the import after changing this config values ?

@AltamashShaikh  Yes, that were the values used when importing.

**Comment by AltamashShaikh** [comment]
> > @miiimooo Can you check what counts do you get by visiting this [tool](https://ga-dev-tools.web.app/query-explorer/)
> > ![Screenshot from 2023-01-12 07-41-17](https://user-images.githubusercontent.com/14902277/211959432-cb9afdbf-011b-4a32-abf7-26158dcbf716.png) for the metrics and dimension combination as mentioned in the screenshot ?
> 
> @AltamashShaikh looking at the request that is made there I notice:
> 
> ![image](https://user-images.githubusercontent.com/1226434/212073732-cf0c1ee6-60f1-480a-ae0d-a674180e6b66.png)
> 
> Could it be that the Importer doesn't have paging support and stops after the `max-results=1000` instead of making another request with `start-index=1001`?

@miiimooo Thanks for sharing this, will prepare a script to test this and update you accordingly
