### ISSUE TITLE
Google Analytics Importer doesn´t work

### ISSUE THREAD

**Issue by Mich-es** [matomo-org/plugin-GoogleAnalyticsImporter#33]
Hi,

i set up the GA-Importer and in the setup all works fine. I start the import. Bute a few hours later - nothing change. After a day - nothing change:
![3d383928e5c3f2ca5f0b3e1f00afa0cf645a2fa3_2_1380x524](https://user-images.githubusercontent.com/58422824/69951190-16c87380-14f5-11ea-81ea-3087779d7a8d.png)

Now i try to import via console - it works - but between 10 an 15 minutes i becaome a terminated:
![8658aff5c46069256ce7655bc4d8adf3f7eed7a6](https://user-images.githubusercontent.com/58422824/69951270-411a3100-14f5-11ea-84f4-b454ab2bcf49.png)

Ok, i found another way - type:
`./console core:run-scheduled-tasks 'Piwik\Plugins\GoogleAnalyticsImporter\Tasks.resumeScheduledImports'

`

and i got an error:

> [Exception]   Task Piwik\Plugins\GoogleAnalyticsImporter\Tasks_resumeScheduledImports not found   Available tasks:

![b9742c9e702a166840f705c248ffad6d86e04dbd_2_1168x1000](https://user-images.githubusercontent.com/58422824/69951361-69a22b00-14f5-11ea-8a1f-9df26bea9435.png)

but i saw a difference in the error:

> Tasks.resumeScheduledImports
Tasks_resumeScheduledImports

What can i do for fix the issue?

**Comment by diosmosis** [comment]
> ./console core:run-scheduled-tasks 'Piwik\Plugins\GoogleAnalyticsImporter\Tasks.resumeScheduledImports'

the command in your screenshot is missing the quotes.

You can try to run the import command with `-vvv` to get more output (see https://matomo.org/docs/google-analytics-importer/#using-the-command-line). Please run the command in that document (`googleanalyticsimporter:import-reports`) with `-vvv` and paste the output.

**Comment by Mich-es** [comment]
No, it doesn´t work.  The qoutes are on it, but ie see the "_" instead of "." i ran it again with -vvv

![google_analytics_importer](https://user-images.githubusercontent.com/58422824/69990711-8c106480-1546-11ea-88e4-e3f666929678.jpg)

**Comment by diosmosis** [comment]
> No, it doesn´t work. The qoutes are on it, but ie see the "_" instead of "." i ran it again with -vvv

That's strange, but it's not related to this plugin (or the "Terminated." error).

Please run the other command described in the user guide I linked to and provide the output.

**Comment by diosmosis** [comment]
Also, can you run `php --version` and paste the output?

**Comment by diosmosis** [comment]
One more question: can you tell me how you're hosting matomo? shared hosting/cloud/...

**Comment by Mich-es** [comment]
`php --version`
`PHP 7.3.11 (cgi-fcgi) (built: Oct 29 2019 14:11:43)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
`
Hosting is shared.

./console googleanalyticsimporter:import-reports --property=UA-XXX-XX --view=XXXX --account=XXXX --idsite=4 -vvv

```
DEBUG [2019-12-03 06:47:20] 28678  Waiting 2s before trying again...
DEBUG [2019-12-03 06:47:22] 28678  Google Analytics returned an error: {
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota group 'AnalyticsDefaultGroup' and limit 'Requests per user per 100 seconds' of service 'analyticsreporting.googleapis.com' for consumer 'project_number:706392440240'.",
    "errors": [
      {
        "message": "Quota exceeded for quota group 'AnalyticsDefaultGroup' and limit 'Requests per user per 100 seconds' of service 'analyticsreporting.googleapis.com' for consumer 'project_number:706392440240'.",
        "domain": "global",
        "reason": "rateLimitExceeded"
      }
    ],
    "status": "RESOURCE_EXHAUSTED"
  }
}

DEBUG [2019-12-03 06:47:22] 28678  Waiting 4s before trying again...
```


I don´t understand this limit - ist was the first time since 2019-11-30
If i run:
`./console googleanalyticsimporter:import-reports --property=UA-XXX-XX --view=XXXX --account=XXXX --idsite=4`

Data was importet, but after 10 to 15 minutes it was terminated:


```
INFO [2019-12-03 06:53:34] 5730  Using existing custom variable slots.
Importing reports for date range 2016-04-15 - 2019-12-03 from GA view XXX.
INFO [2019-12-03 06:53:34] 5730  Importing data for GA View 117078517 for date 2016-04-15...
INFO [2019-12-03 06:54:44] 5730  Found 0 sessions for 2016-04-15, skipping rest of plugins for this day.
INFO [2019-12-03 06:54:44] 5730  Importing data for GA View XXX for date 2016-04-16...
INFO [2019-12-03 06:56:30] 5730  Found 0 sessions for 2016-04-16, skipping rest of plugins for this day.
INFO [2019-12-03 06:56:30] 5730  Importing data for GA View XXX for date 2016-04-17...
INFO [2019-12-03 06:57:47] 5730  Found 0 sessions for 2016-04-17, skipping rest of plugins for this day.
INFO [2019-12-03 06:57:47] 5730  Importing data for GA View XXX for date 2016-04-18...
INFO [2019-12-03 06:59:53] 5730  Found 0 sessions for 2016-04-18, skipping rest of plugins for this day.
INFO [2019-12-03 06:59:53] 5730  Importing data for GA View XXX for date 2016-04-19...
INFO [2019-12-03 07:01:07] 5730  Found 0 sessions for 2016-04-19, skipping rest of plugins for this day.
INFO [2019-12-03 07:01:07] 5730  Importing data for GA View XXX for date 2016-04-20...
INFO [2019-12-03 07:03:17] 5730  Found 0 sessions for 2016-04-20, skipping rest of plugins for this day.
INFO [2019-12-03 07:03:17] 5730  Importing data for GA View XXX for date 2016-04-21...
INFO [2019-12-03 07:04:25] 5730  Found 0 sessions for 2016-04-21, skipping rest of plugins for this day.
INFO [2019-12-03 07:04:25] 5730  Importing data for GA View XXX for date 2016-04-22...
INFO [2019-12-03 07:06:31] 5730  Found 0 sessions for 2016-04-22, skipping rest of plugins for this day.
INFO [2019-12-03 07:06:31] 5730  Importing data for GA View XXX for date 2016-04-23...
INFO [2019-12-03 07:07:51] 5730  Found 0 sessions for 2016-04-23, skipping rest of plugins for this day.
INFO [2019-12-03 07:07:51] 5730  Importing data for GA View XXX for date 2016-04-24...
**Terminated**


```

**Comment by diosmosis** [comment]
> php --version
> PHP 7.3.11 (cgi-fcgi) (built: Oct 29 2019 14:11:43) Copyright (c) 1997-2018 The PHP Group Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
> Hosting is shared.

Is there a CLI php that is accessible to you? For example, `php-cli`, `php7-cli`, etc.? If there is one with the same version, you could try running commands with that instead.

> I don´t understand this limit

That is a rate limiting error, it's not important (the message can be useful for debugging/developing, but not here). You can ignore it.

> Data was importet, but after 10 to 15 minutes it was terminated:

It looks like your host is just terminating processes before they can finish. This is understandable for shared hosting, but it is an issue for this plugin since the import will take a long time no matter what. 

If using the CLI php has the same problem, and your host doesn't want to change any config, then there's one possible workaround. Since the process gets terminated after ~15 minutes, you could setup a cron to run the command every 20 minutes with the --idsite=... parameter (as you did above). This isn't the way the command is supposed to be used, so I'm not 100% sure this will work (I'm a little worried about it affecting the GA daily API request limit), but it's the only workaround I can think of.

Also, I'm about to release a new version in the next couple days, you may want to wait until that release before doing a final import.

**Comment by Mich-es** [comment]
Thanks for help!
I switch matomo until this week to a V-Server and try again an give u a feedback
