### ISSUE TITLE
GA4 Custom dimension not set

### ISSUE THREAD

**Issue by alopetegui** [matomo-org/plugin-GoogleAnalyticsImporter#346]
Importing New property with custom dimensions scoped by action, is not showing the labels of the dimensions.

- The dimensions are event scope, for example in GA4:  
Dimension name: "Cinema Name", 
Use Property/Parameter: "cinema"

When importing the porperty, the custom dimension is imported automatically, however in the panel behaviur, all the custom dimensions has only one row, with the same information:
![image](https://user-images.githubusercontent.com/88507936/218479668-b177678d-898a-4f26-89bb-c7891b1a60ae.png)

I was expecting for example for the cinemaName custom dimension, the count of actions for each cinema name like I have in GA4

**Comment by snake14** [comment]
Hi @alopetegui . Did you manually list that dimension in the custom dimensions list when initiating the import? Reading the [GA Import FAQ](https://matomo.org/faq/general/running-the-google-analytics-import/#importing-unsupported-ga-dimensions), it sounds like only specific GA dimensions are automatically imported and custom ones have to be listed when creating the import. Do you have anything to add @AltamashShaikh ?

**Comment by alopetegui** [comment]
Hi @snake14 , I have tried several attempts and variations to import the data, also I tried creating manually the custom dimensions first as you say, but this creates twice the dimensions and is facing the same issue.
As far as I know, it is not necessary to create manually custom dimension if we are using the plugin to import the property from GA4, as shows this article:[link]( https://matomo.org/faq/how-to/migrate-from-google-analytics-4-to-matomo/). 
_"If you use the GA Importer plugin, they should automatically be created. If not, you’ll probably want to create them manually.."_   (not sure why there is a conditional there)

I think creating manual dimensions are only for standard dimensions in GA4 which are not in matomo

And that's what happens with the import process, my custom dimensions are automatically created, however the proper data is not being fetched.

**Comment by AltamashShaikh** [comment]
@alopetegui 
Can you create a free form with your customDimension and metric `Views` and share the response or can you confirm do you get all the views under `(not set)` ?
![Screenshot from 2023-02-14 14-12-49](https://user-images.githubusercontent.com/14902277/218683954-55822f29-dd09-4793-b005-b61c7be680cc.png)

**Comment by AltamashShaikh** [comment]
> Hi @snake14 , I have tried several attempts and variations to import the data, also I tried creating manually the custom dimensions first as you say, but this creates twice the dimensions and is facing the same issue. As far as I know, it is not necessary to create manually custom dimension if we are using the plugin to import the property from GA4, as shows this article:[link](https://matomo.org/faq/how-to/migrate-from-google-analytics-4-to-matomo/). _"If you use the GA Importer plugin, they should automatically be created. If not, you’ll probably want to create them manually.."_ (not sure why there is a conditional there)
> 
> I think creating manual dimensions are only for standard dimensions in GA4 which are not in matomo
> 
> And that's what happens with the import process, my custom dimensions are automatically created, however the proper data is not being fetched.

@alopetegui and @snake14 CustomDimensions will be created automatically, other one which Matomo doesn't support like `userGender` you can specify such dimensions in the extraDimension slot

**Comment by alopetegui** [comment]
Hi @AltamashShaikh ,

Yes, all the result for "views" metris is (not set), but I have information about other metrics like "Sessions" or "total users"
Is that "behavior" panel only to see view metric? I think since my dimensions are event scope, don't have view metric information but we can see another metrics. Is there a way to see other metrics?

![image](https://user-images.githubusercontent.com/88507936/218686636-30ba2432-a908-453e-81af-8ff20cdc3d8e.png)

**Comment by AltamashShaikh** [comment]
@alopetegui Thanks for checking it quickly, this explains why you were seeing `__not_set_in_google_analytics_4__` 
We query for dimension and the API excludes the empty rows and hence we get only `(not set)` as dimension value.
I have a fix for this, can you edit this [file](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Google/GoogleGA4QueryObjectFactory.php#L92) and add below code before return ? and re import for any date range which has values and check if you can see the same in Matomo ?
```
$body['keepEmptyRows'] = true;
```

**Comment by alopetegui** [comment]
@AltamashShaikh , thanks, now the importer is showing the custom dimensions.
but one question, it seems that is only taking "Unique Actions", because the rest of the columns are 0 or 100%, is that normal?
![image](https://user-images.githubusercontent.com/88507936/218711888-9fe126ff-2540-45c6-9dc5-4bb20e3574fe.png)

**Comment by AltamashShaikh** [comment]
@alopetegui Yes, reason we don't get the desired metrics to convert the data from GA4 api and thanks for checking quickly :+1:, we have prepared a PR - #350 to resolve this issue

**Comment by alopetegui** [comment]
@AltamashShaikh , I have tried the #350 Pull Request, and the issue with __not_set_in_google_analytics_4__ is fixed, but still there is no data for the rest of the metrics.

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh , I have tried the #350 Pull Request, and the issue with **not_set_in_google_analytics_4** is fixed, but still there is no data for the rest of the metrics.

@alopetegui We couldn't find the equivalent metrics in GA4
In GA3 we were dependent on `'ga:timeOnPage`, `ga:pageDownloadTime` and `ga:pageLoadSample` metrics to calculate the other columns.
You can read about those metrics [here](https://ga-dev-tools.web.app/dimensions-metrics-explorer/page-tracking#timeOnPage)
Also referred this [mapping](https://developers.google.com/analytics/devguides/migration/api/reporting-ua-to-ga4-dims-mets) given by Google to map the metrics

**Comment by alopetegui** [comment]
@AltamashShaikh , are you planing to change to another valid metrics in GA4? as you know GA3 (Universal Analytics)  will be going away [ **On July 1, 2023**](https://support.google.com/analytics/answer/11583528?hl=en). I think the Google Analytics importer should be already using GA4 metrics.

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh , are you planing to change to another valid metrics in GA4? as you know GA3 (Universal Analytics) will be going away [ **On July 1, 2023**](https://support.google.com/analytics/answer/11583528?hl=en). I think the Google Analytics importer should be already using GA4 metrics.

@alopetegui Sorry I didn't get you

**Comment by alopetegui** [comment]
@AltamashShaikh , I'm asking if you are going to change the columns on "Behaviour" panel, or the way you calculate those columns in order to use GA4 metrics, because I'm using GA4 and furthermore because  GA3 will be discontinued on July 1.

I think in those columns there should be GA4 metrics, have I explained it well?

**Comment by AltamashShaikh** [comment]
@alopetegui currently thats not in plan
Do you have an idea about the equivalent metrics in GA4?

**Comment by alopetegui** [comment]
@AltamashShaikh , as you shared with me there is a mapping information [here](https://developers.google.com/analytics/devguides/migration/api/reporting-ua-to-ga4-dims-mets)

There are some metrics that have equivalences but others not,
This metrics have equivalent:
ga:timeOnPage -> userEngagementDuration

Others I cant' find it:
ga:pageDownloadTime
ga:pageLoadSample

On the other had, bounce rate doesn't' exist on GA4, but for similar metric they use "engagement rate". This metric is calculated by dividing the number of engaged sessions by the total number of sessions. It's like the inverse of "Bounce Rate", so "Bounce rate" = 100%-"Engagement rate"

I guess that matomo is more similar to GA3 than GA4, but now that GA3 is going to deprecate, I don't know if you should adapt matomo to be more equivalent to GA4, but this is a decision in your side.

**Comment by AltamashShaikh** [comment]
> Bounce

@alopetegui Adding `ga:timeOnPage -> userEngagementDuration` and we are calculating `bounce_rate` see [this](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Google/GoogleGA4MetricMapper.php#L111) and for rest we aren't inclined to change just because 1 source is incompatible, we might incorporate new metrics if Google adds it

**Comment by AltamashShaikh** [comment]
@alopetegui Closing this since we have added `$body['keepEmptyRows'] = true;`
