### ISSUE TITLE
Allow importing only a specific data stream

### ISSUE THREAD

**Issue by alopetegui** [matomo-org/plugin-GoogleAnalyticsImporter#353]
Sometimes you may want to import only a specific data stream instead of all property , probably to separate the property in different websites in matomo.

It would be nice to be able to define the stream_id in the import configuration, to only get the data from that datastream,

It could be defined in the import configuration something like this:
 properties/{property_id}/webDataStreams/{stream_id}

or adding another field for the stream id

**Comment by snake14** [comment]
Thank you @alopetegui . I'm adding this to our backlog to be prioritised.

**Comment by snake14** [comment]
@AltamashShaikh any concerns you can think of or any reason we wouldn't be able to implement this improvement?

**Comment by AltamashShaikh** [comment]
@alopetegui @snake14 I don't think the API supports this, checked the [API documentation](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport?) and it doesn't seems to support it, and gives an error `property does not match pattern: /^properties\/[^/]+$/`

**Comment by alopetegui** [comment]
@AltamashShaikh , but you can filter for an extra dimension by default when you define the stream_id.
I mean, if you configure the import defining the stream_id, you could filter all the queries you do in the importer adding the stream_id filter at the end, that way you will take only the data from that datastream.

This is something that I'm hardcoding now because I need it to import the different datastreams in different sites.
    'dimensionFilter' => [
        'dimension' => 'streamId',
        'filterType' => 'inList',
        'filterValue' => ['XXXXXXXXXXXXXX']
    ]       
  ]

Not sure, if it is better to user "filterType" "inList", or there is a better filter, but this works for me.

Can you add streamId as a configuration parameter?

**Comment by AltamashShaikh** [comment]
@alopetegui Adding it via dimensionFilter should work :+1: , we have added this for prioritisation and our product team will check and plan this.

We are also happy to merge a PR, if you are willing to implement this feature

**Comment by alopetegui** [comment]
Thanks a lot @AltamashShaikh 

I don't know if I will be able to do a PR, but If I can, will do it, thanks again.
