### ISSUE TITLE
Where can I modify the invocation of php?

### ISSUE THREAD

**Issue by zigojacko** [matomo-org/plugin-GoogleAnalyticsImporter#360]
![Screenshot_2](https://user-images.githubusercontent.com/849735/221835324-16adabb5-8c3f-4a3c-a687-f28725026606.jpg)

The space that is running Matomo is running PHP 8 but if you are invoking PHP from the command line as per the above, then this will be returning PHP 5.6 (the server runs all PHP versions from this version) so therefore, this plugin is not working for me.

Is there somewhere I can modify the commands that the plugin is running, I just need to add a line that forces the switch to the relevant PHP binary if this is possible...?

**Comment by AltamashShaikh** [comment]
@zigojacko You want to set the `php_binary_path` right ?
You can try setting it via config setting
```
[General]
php_binary_path = /your/path
```

Also if you want to modify the command, check here
GA3 - https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Tasks.php#L116
GA4 - https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Tasks.php#L169

**Comment by zigojacko** [comment]
I am unsure why but when I specify the `php_binary_path` in the config file, it makes absolutely no difference and still states in the system check that the PHP executable can't be found. 🤷‍♂️

**Comment by zigojacko** [comment]
Furthermore, I've even removed PHP 5.6 from the server completely now so I only have PHP 7 and PHP 8 on here now. I don't appear to be able to get the system check to see the PHP executable - I've tried everything I can think of including modifying the Tasks.php file with the direct path to the PHP 8 binary.

**Comment by AltamashShaikh** [comment]
@zigojacko This is are the commands to import GA data into Matomo
GA4 - `php console googleanalyticsimporter:import-ga4-reports  --property="properties/{PROPERTY_ID}" --dates=start_date,end_date`

GA3 - `php console googleanalyticsimporter:import-reports --property={PROPERTY_ID} --view={VIEW_ID} --account={ACCOUNT_ID} --dates=start_date,end_date`

What will be the correct command for you ?

**Comment by zigojacko** [comment]
@AltamashShaikh well the path to PHP is `/opt/plesk/php/8.2/bin/php` but like I say, setting this as the `php_binary_path` doesn't fix the errors in my above screenshots. I don't really know why though. The importer hasn't worked for me - presumably due to these errors - so I am just trying to clear these errors first before I try again. But I do not know why it can't see PHP - it is obviously there and exists.

**Comment by AltamashShaikh** [comment]
@zigojacko 
I tried setting this config and it works, the code check if the config value is set and also file_exists for the php_binary_path, so maybe check if you are getting any permission issue maybe on your webserver
```
[General]
php_binary_path = "/usr/bin/php"
```

**Comment by zigojacko** [comment]
@AltamashShaikh whatever you did in your latest update (4.5.1) for nohup fixed this issue I reported in my first comment with the screenshot showing that it could not find the executable. There was no other changes made and that error was fixed.

So I am just left with this PHP executable issue - is there not a similar change you can make for it to also detect that successfully?

**Comment by AltamashShaikh** [comment]
@zigojacko can you run this in your terminal `which php` ? and share the output ?

**Comment by zigojacko** [comment]
@AltamashShaikh 

Yes sure, it is here:

```
[root@panel ~]# which php
/usr/bin/php
```

But that version is the vendor default which is 5.4...

```
[root@panel ~]# php -v
PHP 5.4.16 (cli) (built: Apr  1 2020 04:07:17)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
```

The actual version needed for the domain hosting Matomo is located here:

`/opt/plesk/php/8.2/bin/php`

```
[root@panel ~]# /opt/plesk/php/8.2/bin/php -v
PHP 8.2.3 (cli) (built: Feb 20 2023 18:38:19) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.3, Copyright (c), by Zend Technologies

```

**Comment by AltamashShaikh** [comment]
@zigojacko Did you try setting `php_binary_path = "/opt/plesk/php/8.2/bin/php"` it in `config.ini.php` under `[General]` ?

**Comment by AltamashShaikh** [comment]
![Screenshot from 2023-03-14 19-05-53](https://user-images.githubusercontent.com/14902277/225017958-00dba401-9b62-44df-a7a2-63f5960876f7.png)
Something like this

**Comment by zigojacko** [comment]
@AltamashShaikh yes, it is already set to that and it doesn't work - this is what I've been reporting for weeks 😆

![Screenshot_8](https://user-images.githubusercontent.com/849735/225021039-a4379fc7-4e87-4cca-974c-e4a11bb6d23e.jpg)

**Comment by AltamashShaikh** [comment]
@zigojacko file_exists might be failing for you as per this [line](https://github.com/matomo-org/matomo/blob/4.x-dev/core/CliMulti/CliPhp.php#L19)

**Comment by zigojacko** [comment]
@AltamashShaikh how do you mean exactly? The file does exist and we're not receiving any errors to say otherwise.

**Comment by AltamashShaikh** [comment]
@zigojacko Create a file `test_php_path.php` under your `/matomo/path`
```
<?php

$path = '/usr/bin/php';

var_dump(file_exists($path));
```
access this file via your webserver `https://your-matomo-domain/test_php_path.php` and check the response

**Comment by zigojacko** [comment]
@AltamashShaikh it returns `bool(false)` but should the path be to my 8.2 Plesk version and not the default OS version?

**Comment by AltamashShaikh** [comment]
> @AltamashShaikh it returns `bool(false)` but should the path be to my 8.2 Plesk version and not the default OS version?

@zigojacko The path should be accessible by your webserver user for eg if its apache check this works `sudo -u apache ls -l /usr/bin/php`

**Comment by zigojacko** [comment]
@AltamashShaikh the web server user that owns the Matomo files will not have access to the path to the PHP binary - if that is what you are saying. Because those locations are all owned by root. The user that owns the files is chrooted to it's web space - that's just a typical Plesk environment.

```
[root@panel httpdocs]# sudo -u theclubnetgroup.com_bsx1ds47iz ls -l /usr/bin/php
-rwxr-xr-x. 1 root root 4618080 Apr  1  2020 /usr/bin/php
```

**Comment by AltamashShaikh** [comment]
@zigojacko does removing the file_exist check from this file `core/CliMulti/CliPhp.php` works for you?
https://github.com/matomo-org/matomo/blob/4.x-dev/core/CliMulti/CliPhp.php#L19

**Comment by zigojacko** [comment]
@AltamashShaikh I am unsure what you mean by "works for you" exactly but by commenting out the `file_exists` check, it does remove the error and shows as a green check in the System yes - so it does look good in that respect...

![Screenshot_5](https://user-images.githubusercontent.com/849735/225058345-3a097778-554b-4f03-b1bc-e56bbb084a9d.jpg)

![Screenshot_6](https://user-images.githubusercontent.com/849735/225058375-0fd3465a-cb04-4b14-aeb9-5827609a2406.jpg)

**Comment by AltamashShaikh** [comment]
And now if you schedule a import does that works?

**Comment by zigojacko** [comment]
@AltamashShaikh oh I don't know, I will give it a go and come back here and let you know.

Thanks very much for helping me to get this sorted.

**Comment by zigojacko** [comment]
@AltamashShaikh well something IS definitely happening now but it's nowhere near the correct data yet...

![Screenshot_6](https://user-images.githubusercontent.com/849735/225255701-3a56d312-e99e-4dcf-926e-85f3833d7074.jpg)

![Screenshot_5](https://user-images.githubusercontent.com/849735/225255189-dca0ccba-9ece-4d34-849c-e62955a64643.jpg)

Not really sure how long it should take but if I compare the same period (01/01/2022 - 14/03/2023) to the GA3 account, then the visits should be over 200,000 and the revenue over £800k but it is showing 35,716 visits.

But it has (or is still, I don't know) definitely importing data.

**Comment by AltamashShaikh** [comment]
@zigojacko check for a day or couple of days I would say
That would give you a better overview

**Comment by zigojacko** [comment]
Thanks @AltamashShaikh - I will just check it again tomorrow and see.

Hopefully we've got this sorted though now fingers crossed. Thanks for helping to figure that out with me 👍

**Comment by zigojacko** [comment]
@AltamashShaikh so looking at the same data today as I posted above yesterday, basically the data in Matomo has doubled - so it is still way off what it should be...

Is this import meant to take several days to pull in from GA3? It is fine if this is common, I just can't work out if it is working correctly or not at the moment 😅

**Comment by AltamashShaikh** [comment]
Compare from endDate to lastDayArchived all should be good hopefully

**Comment by zigojacko** [comment]
I am not sure where to find those but I noticed this...

![Screenshot_3](https://user-images.githubusercontent.com/849735/225876719-44d5a060-0e82-48ac-bc7a-c3610f26028f.jpg)

So looks like all the data importing is being throttled to 50,000 requests a day. I was trying to import the entire history from GA3 so this would be several year's worth... I've got no idea what has or hasn't imported nor where we're up to...

**Comment by AltamashShaikh** [comment]
@zigojacko The limit is from Google's end and as you see Last Day Imported field you can check the data till that day in GA and compare it with Matomo
