### ISSUE TITLE
Import killed after 300 sec

### ISSUE THREAD

**Issue by prathers** [matomo-org/plugin-GoogleAnalyticsImporter#365]
I have earlier done an import with succes. 

Now when enabling another GA, it stops after 300 seconds and the interface returns

"Killed

It looks like the import job was terminated. If you didn't do this yourself, then your host probably does not like long-running PHP processes. The import job will start again within the next hour so the import will still continue. If the import speed is still slow overall (check back in a day to see), then view the user guide for more information and workarounds." 

I've tried through the CLI and through FPM with same result.

Running a `php console googleanalyticsimporter:import-reports --idsite={GAsite-id} -vvv`

returns:

>Resuming import into existing site {ID}.
INFO [2023-03-07 20:07:18] 1811  Using existing custom variable slots.
Importing the following date ranges in order:
Done in Time elapsed: 0.827s. [0 API requests made to GA]

GA-import v4.5.0

Matomo v4.13.3

PHP v8.1

**Comment by snake14** [comment]
Hi @prathers . I'm sorry to hear that you're experiencing this issue. It looks like you're running the latest version of Matomo and the plugin, so that's good. It's odd that when you ran the import using CLI it says that it didn't make any API requests. It also doesn't show the date range. What date range do you have configured for the import? Were there any errors in your Matomo log?

**Comment by AltamashShaikh** [comment]
@prathers You can try running a new import using CLI or via the UI with verbose logging enabled and check if you see any errors.
![Screenshot from 2023-03-08 06-44-24](https://user-images.githubusercontent.com/14902277/223593885-0443b258-bbf6-4bae-8aff-f8653656315b.png)

Cli command `php console googleanalyticsimporter:import-reports --property={PROPERTY_ID} --view={VIEW_ID} --account={ACCOUNT_ID} --dates=start_date,end_date -vvv`

**Comment by prathers** [comment]
I manage to get it started with the CLI - still not sure why it kept stalling. The start_date was 2023-03-07 (today)

I will get back with a full report when I can see teh import is stabilised

**Comment by prathers** [comment]
Just a followup: Can it be that it is only possible to make one import at a time? I have four GA's that I need to import..

**Comment by AltamashShaikh** [comment]
@prathers currently couldn't find a way, I would recommend you to schedule one at a time for now

**Comment by AltamashShaikh** [comment]
@prathers You can do something like this, if you are comfortable - https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/issues/242#issuecomment-1451497314

**Comment by prathers** [comment]
Splendid! Thanks a million
