### ISSUE TITLE
GA4 API can return 0 sessions, but other data can exist

### ISSUE THREAD

**Issue by Starker3** [matomo-org/plugin-GoogleAnalyticsImporter#367]
It seems as though the GA4 API can return a `0` value for the `Sessions` metric, but the data does actually still exist when checked through the UI:
![image](https://user-images.githubusercontent.com/20905821/224600900-cbf7d869-0d57-4a1c-bee1-946e0e397fe0.png)
The API returns the following:
![image](https://user-images.githubusercontent.com/20905821/224600935-0d087dd8-1d23-4206-94dc-b309500a1900.png)

This means that our importer would skip the imports and archiving of this period, resulting in no data being imported:
![image](https://user-images.githubusercontent.com/20905821/224601090-6c83f6a7-76f9-4e70-ab33-a51b8e1a751a.png)

(For some reason there was reports showing but just for a single metric only such as number of Actions, but no other data).

When we comment out the check for if there are visits (I.e. to force the import and archive regardless of if there are sessions):
```
$sessions = $visitsSummaryRecordImporter->getSessions();
if ($sessions <= 0) {
    $this->logger->info("Found 0 sessions for {$date} [segment = $segment], skipping rest of plugins for this day/segment.");
    break;
}
```

Then we can at least get some data imported:
(This period looks like it has valid visits data, or at least partially)
![image](https://user-images.githubusercontent.com/20905821/224602090-2ceb1ceb-f5c0-472e-b345-4c3c2bb9e3b6.png)
This week period shows actions only, but no unique visitor data which is shown for the day period below:
![image](https://user-images.githubusercontent.com/20905821/224602196-b6a18c1c-cb67-40a6-83be-098f2af006e5.png)
![image](https://user-images.githubusercontent.com/20905821/224602337-8b5430fc-cdcb-4d24-9b3b-9c050c30ba41.png)

**Comment by AltamashShaikh** [comment]
@Stan-vw We can discuss if this should be implemented for all imports or an option should be given, when we schedule this

**Comment by Starker3** [comment]
To provide some clarity on this issue:
Basically there seems to be a bug in the GA API (Not sure if only GA4?) where periods older than a specific date return 0 for the 'Sessions' metric.

The GA Importer plugin has a simple check to see if there are any sessions for the imported period and if there are 0 it skips the archiving of that period. But in this case there is other data, but not sessions.

Altamash's comment (based on my discussion with him) would basically be something like a checkbox in the UI when starting an import that would be something like "Disable check for sessions"

If I didn't understand your comment, feel free to add some more details @AltamashShaikh

**Comment by AltamashShaikh** [comment]
@Starker3 Yes correct in GA3 for older dates API data is not same as Google UI data and we do see `0` sessions and yes its a decision to be taken to have a checkbox or import 0 sessions data by default

**Comment by AltamashShaikh** [comment]
Had a call with @Stan-vw  and its best to not create any checkbox in the UI and rather improve the check from `$sessions <=0` to check if the `VisitsSummary` `hasSomeData` and based on that continue or skip the import for the day

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/ga4-import-doesnt-work-before-specific-date/50343/11
