### ISSUE TITLE
Add clear information about adding an end date to the import

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/plugin-GoogleAnalyticsImporter#371]
**Issue**: Add information about setting the import end date in the UI

**Context**: When configuring an import from GA, when the end date is not set there is an impression that it will keep importing and our FAQ suggest that as well (FAQ getting updated), however with the current logic , if importDate is 1st March 23 - 17th March 23
We will pull data for 16th of March to start with and  then 15th until it reaches the start date and then we import 17th of March. Which makes setting up the end date mandatory.

**Suggestion**: Information about adding the end date in the configuration would be helpful

**From customer**: After following all of the outlined steps to set up the GA Importer Plugin, we can still not get the continuous data import from GA to work (since I am still tracking in GA but want the data transferred to Matomo). Currently, I am having to patch data together using the re-import tool. Can you please look into this issue and recommend any solutions? This has been extremely frustrating to resolve...

**Comment by AltamashShaikh** [comment]
@KarthikRaja1388 Do we still want the continuous import option enabled ? or just mentioning about recent dates import first should be fine ?

**Comment by KarthikRaja1388** [comment]
@AltamashShaikh continuous import is causing some issues, so it would be better add a clear message about adding end date
