### ISSUE TITLE
Failed Security Check

### ISSUE THREAD

**Issue by mindbreaker** [matomo-org/plugin-GoogleAnalyticsImporter#376]
When I perform an import, it fails. 

/logs/gaimportlog.3..log

```
X-Matomo-Request-Id: c8418
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: MATOMO_SESSID=......; expires=Mon, 10-Apr-2023 16:38:53 GMT; path=/; secure; httponly; SameSite=Lax
Content-type: text/html; charset=UTF-8

<div class="alert alert-danger">
                <p><strong>Error:</strong> We&#039;re sorry, but the action you were trying to perform failed due to a security check. This is a standard measure to ensure the safety and security of your account. Please try again, and if the issue persists, please contact our support team for further assistance.</p>
                <p><a href="index.php?module=Login">Sign in</a></p>
            </div>
```

**Comment by snake14** [comment]
Hi @mindbreaker . I'm sorry that you experienced this issue. Have you checked our [knowledge base](https://forum.matomo.org/) for any information? I believe that error usually occurs when an action is performed after sitting on the page too long and the security token has expired. Does it work if you refresh the page and then immediately run the import? If that doesn't work, please try [running the import from the terminal](https://matomo.org/faq/general/running-the-google-analytics-import/#setup-an-import-using-the-command-line-for-universal-analytics-ga3) with the `--verbose` option. I'm going to close this issue, but please let us know if you feel it needs to be reopened.
