### ISSUE TITLE
"An error occurred" message after... update??

### ISSUE THREAD

**Issue by sdiama** [matomo-org/plugin-GoogleAnalyticsImporter#384]
I had setup the plugin and started the import of multiple sites. The processes was running successfully for a couple of months.
After the update to v4.6 I notice that a GA4 import that was running could not proceed and stuck at the last imported date (April 3). Unfortunately I didn't keep the error message. Trying to manualy restart the import ended with the same error.
So, I decided to remove client configuration and restart the plugin setup process. I uploaded the oAuth JSON, but when I try to authorize matomo I got the error:
_"We're sorry, but the action you were trying to perform failed due to a security check. This is a standard measure to ensure the safety and security of your account. Please try again, and if the issue persists, please contact our support team for further assistance."_

Any help will be greatly appreciated.

**Comment by AltamashShaikh** [comment]
@sdiama This looks like your token expired can you refresh the page and retry if it works?

**Comment by sdiama** [comment]
@AltamashShaikh Unfortunately not. I've tried multiple times to refresh the page, with soft and hard refresh.
I also cleared my Matomo installation's cookies and all Google related cookies. In this case after the authorize I re-enter my Google credentials, but the result is still the same!

**Comment by sdiama** [comment]
I manage to find, that the error is returned from Matomo's core/Nonce.php. The error is:
_"The form security failed because the "Referer" header is different from what was expected. Check that it is sent correctly."_

More specific the **checkNonce()** has third argument the **$allowedReferrerHost**. The value passed in this one is "google.com". The value of the argument is checked at Nonce against the **Url::getHostFromUrl()** which correctly returns my Matomo's installation URL and when is checked with **isReferrerHostValid()** returns false.

I just repeat, that nothings has been changed on my configuration except from the regular proposed updates for Matomo and GoogleAnalyticsImporter.

**Comment by AltamashShaikh** [comment]
@sdiama can you comment that line for now and try and proceed ahead?
Will take a look on Monday if something has regressed or not

**Comment by AltamashShaikh** [comment]
@sdiama I was able to reproduce this one, the issue is now the referrer being returned is specific to your region for me it was `https://accounts.google.co.in` and we are doing `preg_match` for `google.com` which will fail.

**Comment by AltamashShaikh** [comment]
@sdiama Can you apply the changes of https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/pull/385 and check if it solves your issue ?

**Comment by sdiama** [comment]
Yes, I'll try to check it later in the afternoon.

**Comment by AltamashShaikh** [comment]
@sdiama Did you get a chance to check it ?
