### ISSUE TITLE
Simplify the setup / configuration of GA Importer 

### ISSUE THREAD

**Issue by tsteur** [matomo-org/plugin-GoogleAnalyticsImporter#396]
Currently, the guide to set up GA is a lot of steps and takes quite a while see https://matomo.org/faq/general/set-up-google-analytics-import/ 

Could we have an option that has less steps by doing it similarly to Zoho by using a cloudshell script? See https://www.zoho.com/mail/help/adminconsole/gsuite-authorization.html#json-method

This way the user would only need to copy/paste the shell script rather than going through all the steps themselves.

**Comment by AltamashShaikh** [comment]
@tsteur a good way to simplify the Oauth :+1: 
may be we can add this a command which can do the same
