### ISSUE TITLE
Bug for Matomo when installing GoogleAnalyticsImporter plugin (Piwik\SiteContentDetector)

### ISSUE THREAD

**Issue by Kayoku** [matomo-org/plugin-GoogleAnalyticsImporter#404]
Hi,

First, Thank you really much for this plugin.

I had a bug on my instance of Matomo (4.10.1) when installing the last version of GoogleAnalyticsImporter (4.6.4). After that I installed and enable the plugin, and Go to the menu below

![screenmenu](https://i.postimg.cc/BZxKzWg6/Capture-d-cran-de-2023-05-15-14-50-30.png)

I got the error 

```
matomo google import Error while injecting dependencies into Piwik\Plugins\GoogleAnalyticsImporter\Controller: No entry or class found for 'Piwik\SiteContentDetector'
```

After some reseach, I found that the `use Piwik\SiteContentDetector` was added on [this commit](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/commit/8bd02c1611d0b6b519b424b0d8b5803517f5b985) the 17 February 2023. I think this is related, but maybe you know that better than me !

To "fix" the issue, I installed the version before the commit (4.4.8) and it works.

**Comment by snake14** [comment]
Hi @Kayoku . Our apologies. It looks like the minimum Matomo version should have been updated to [4.13.0](https://github.com/matomo-org/matomo/releases/tag/4.13.0) when that class was added to the plugin.

@AltamashShaikh Do you think it would be better to find a way to remove Piwik\SiteContentDetector usage from the plugin or to update the minimum Matomo version?

**Comment by AltamashShaikh** [comment]
@snake14 will remove the usage and use it only when class is available

**Comment by AltamashShaikh** [comment]
@Kayoku Created https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/pull/405 to tackle this issue, thank you for letting us know :+1:
