### ISSUE TITLE
Adding a transformation to change domain name of URLs while importing from GA

### ISSUE THREAD

**Issue by Hen0k** [matomo-org/plugin-GoogleAnalyticsImporter#406]
This is for an import I am currently doing. If someone could point me to the place where I need to add this feature, I want to try to do it. I want to change the domain names of the URLs that are being imported to some other URL based on a custom mapping rule.

**Comment by snake14** [comment]
Hi @Hen0k . Thank you for taking the time to create this issue and consider making an enhancement to the plugin. I'm not completely sure how you would go about making that change, but I'm thinking that it would probably require updating the `makeSite()` method in both Importer.php and ImporterGA4.php. You'd probably want to create a new configuration to define the custom mapping rule. Anything you'd like to add @AltamashShaikh ?

**Comment by AltamashShaikh** [comment]
@Hen0k you can update this [line](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/ImporterGA4.php#L190) of code for GA4
```
'urls' => [{MY_CUSTOM_URL}],
```

**Comment by Hen0k** [comment]
Thanks @snake14  and @AltamashShaikh for the quick response. The make site function wasn't what I was looking to change. It was the url in the acctual data I was importing. I found the solution on this [line](https://github.com/henoktilaye/plugin-GoogleAnalyticsImporter/blob/810e77310c9870224de1f8800dfcb41e1c3ad565/Importers/Actions/RecordImporter.php#L322)
