### ISSUE TITLE
Error 504 with authorizing Google Analytics

### ISSUE THREAD

**Issue by afgborsboom** [matomo-org/plugin-GoogleAnalyticsImporter#413]
We experience problems with authorizong matomo and google analytics.

According to the instructions we created a JSON file. When we upload it in matomo google analytics importer and press the button authorize the next screen asks for the google analytics loginname, confirmation goes OK. Then we confirm the warning about the unverified app. After that we give the final confimation and apply.
Then de screen keeps on “loading” till is reaches a 504 - Gateway timeout. We cannot find out where it goes wrong. Can someone give us a hint or solution?

System: Linux RHEL 8.7
Nginx 1.24.0
Matomo: 4.14.2
PHP: 8.1.19
SQL: 8.0.30
Google Anayltis Importer: 4.6.5
Browser: Edge or Chrome latest editions
OS: Windows 10
![errornginx](https://github.com/matomo-org/matomo/assets/125553958/3d921727-6c9d-494a-8198-c2fd62c4e596)
![loading1](https://github.com/matomo-org/matomo/assets/125553958/ce79497a-15c9-4330-80a6-ea53f8928b0d)

**Comment by snake14** [comment]
Hi @afgborsboom . I'm sorry to hear that you're experiencing this issue. Are you seeing any errors in your Matomo server log? Just to confirm, when you were setting up your config, you used the following as your redirect URL? `https://{your_domain}/index.php?module=GoogleAnalyticsImporter&action=processAuthCode`

**Comment by afgborsboom** [comment]
Hi JacobR,

I checked but is see sometimes, but not always this errorline:

2023/06/13 09:53:26 [error] 1589#1589: *199 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 141.105.145.19, server: matomo.spzl.nl, request: "GET /index.php?module=GoogleAnalyticsImporter&action=processAuthCode&state=b06f59dc3eb9b2ae4f6e0f1a7656e682&code=4/0AbUR2VMvsSB4wjT0qoYW0FwnA-3IyvssvGl8PBmWfkZNVj8yhWErqzrax-6Dr57ixf1LQw&scope=https://www.googleapis.com/auth/analytics.readonly HTTP/1.0", upstream: "fastcgi://unix:/run/php-fpm/www.sock", host: "matomo.spzl.nl", referrer: "https://accounts.google.com/"



. Below the complete url link which is in the JOSN file ( keys are left out)

{"web":{"client_id":"xxxxxxx-2907fhdkl7pfh3rouop6lqpuut2onis4.apps.googleusercontent.com","project_id":"test-gm-project-389217","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"XXXXXXXXXXXXXXXXXXXXXXXX","redirect_uris":["https://xxxxxxx.nl/index.php?module=GoogleAnalyticsImporter&action=processAuthCode"],"javascript_origins":["https://xxxxxxx.nl"]}}


________________________________
Van: Jacob R ***@***.***>
Verzonden: maandag 12 juni 2023 22:49
Aan: matomo-org/plugin-GoogleAnalyticsImporter ***@***.***>
CC: afgborsboom ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [matomo-org/plugin-GoogleAnalyticsImporter] Error 504 with authorizing Google Analytics (Issue #413)


Hi @afgborsboom<https://github.com/afgborsboom> . I'm sorry to hear that you're experiencing this issue. Are you seeing any errors in your Matomo server log? Just to confirm, when you were setting up your config, you used the following as your redirect URL? https://{your_domain}/index.php?module=GoogleAnalyticsImporter&action=processAuthCode

**Comment by snake14** [comment]
Thank you for the additional information @afgborsboom . I notice that the scope of the request URL ends in `.readonly`. I believe that we've had some customers have issues with their server configuration excluding URLs that end that way. Could you please check your Nginx configuration to make sure that it's not excluding requests to endpoints ending with readonly? Anything else you'd recommend checking @AltamashShaikh ?

**Comment by AltamashShaikh** [comment]
@snake14 I tried checking if the URL params like `.readonly` creates any issue or not by hitting the Matomo URL of @afgborsboom and it doesn't looks like that is the case.

@afgborsboom Can you check if increasing your nginx timeout fixes the issue ?
This might be related to your webserver config, you can also check by adding `die('Function breakpoint reached');` [here](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Controller.php#L243) in your webserver and check if this still results in 504

**Comment by afgborsboom** [comment]
@AltamashShaikh  Thanks for the reply. When i increase timeout nothing changes. error 504 keeps coming

when i enter the line in the controller.php file. i get a response as in the screenshot attached
![function](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/assets/125553958/4791fb56-249b-4224-947b-0093b52ebcd4)

**Comment by AltamashShaikh** [comment]
@afgborsboom Do you have any error in the `matomo.log` file when you remove the `die` statement and try again ?
Or any other error in nginx error.log file ?
I am just trying to narrow it down this issue, as we are seeing this issue for the first time

**Comment by afgborsboom** [comment]
@AltamashShaikh No problem. It is very strange.

I see nothing in the error log, however in the access log i see some entries. I have attached that file. It looks if it is waiting for something or tries to get access and then has a timeout.

[GA.txt](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/files/11742868/GA.txt)

**Comment by AltamashShaikh** [comment]
@afgborsboom I reckon you have to play with that die statement by moving it after this [line](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Controller.php#L247) and below lines to see what is actually taking time

**Comment by afgborsboom** [comment]
@AltamashShaikh Thanks for the response. I found the possible statement where it stops.

**Nonce::checkNonce(self::OAUTH_STATE_NONCE_NAME, $state, 'google.com');

        if ($error) {
            return $this->index($error);
      die('Function breakpoint reached');
        }**

The first line he passes (The Nonce line). I then get the "die" statement. but if i insert the "die" statment after where it says "if($....) it stops and keeps loading till the timout was reached. It does not reached the "die" statement". ( Lines 254 end 255).

it seems to go wrong in those 2 lines

**Comment by AltamashShaikh** [comment]
@afgborsboom Does changing 2 problematic lines with this code makes it work?
```
if (!empty($error)) {
      return $this->index($error);
}
```

**Comment by afgborsboom** [comment]
@AltamashShaikh  sorry. stays the same, timeout error

**Comment by AltamashShaikh** [comment]
@afgborsboom I think there is some error in the request, thanks for quick replies
Can you update the nonce ttl to 120 instead of 1200 in all the places mentioned in this part of code ?
https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Controller.php#L75..L95

**Comment by afgborsboom** [comment]
@AltamashShaikh done - but sadly nu succes

**Comment by AltamashShaikh** [comment]
@afgborsboom I think you should try to print the error message and if there is no error message you can comment that 2 lines and try
Add this after this [line](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Controller.php#L244)
```
var_dump($error);
die('Function breakpoint reached');
```

**Comment by afgborsboom** [comment]
Good Morning @AltamashShaikh When i add that line i get this

_string(0) "" Function breakpoint reached_

What do you mean by comment that 2 lines?

**Comment by AltamashShaikh** [comment]
Goodmorning @afgborsboom 
I meant updating this [lines](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Controller.php#L254..L256)
```
/**
        if ($error) {
            return $this->index($error);
        }
**/
```

**Comment by afgborsboom** [comment]
@AltamashShaikh . i do net get an error. only the die statement. When i leave that die stament away it keeps on loading. it looks if it goes wrong in the next statement

/** @var Authorization $authorization */
            $authorization = StaticContainer::get(Authorization::class);

**Comment by AltamashShaikh** [comment]
@afgborsboom that's strange, can you add a die statement after `$authorization = StaticContainer::get(Authorization::class);` and see if it executes ? if it does can you keep moving die statement after 1-1 line to determine which line is problematic for you ?

**Comment by afgborsboom** [comment]
@AltamashShaikh - check. it stops after this statement

 try {
            /** @var Authorization $authorization */
            $authorization = StaticContainer::get(Authorization::class);
            $client = $authorization->getConfiguredClient();
            $authorization->saveAccessToken($oauthCode, $client);
            die('Function breakpoint reached');

The die statement still works if i put it between $Client  en $Authorization lines (Lines 262 & 263), so it stop at this line

$authorization->saveAccessToken($oauthCode, $client);

**Comment by AltamashShaikh** [comment]
@afgborsboom I believe there might me some issue in your Oauth step maybe ?
You can add the die statement [here](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Google/Authorization.php#L64) and check which line it fails

**Comment by afgborsboom** [comment]
When i insert the statement below this line. it keeps loading and times out

 $accessToken = $client->fetchAccessTokenWithAuthCode($oauthCode);
        die('Function breakpoint reached');

**Comment by AltamashShaikh** [comment]
@afgborsboom I am afraid to inform you there seems to be no issue in the plugin, check https://stackoverflow.com/questions/71182941/google-php-api-client-fetchaccesstokenwithauthcode-not-working, you might need to check with different server/network maybe to see if issue persist?

**Comment by afgborsboom** [comment]
@AltamashShaikh thanks for the support. We test with dockerized matomo and there the import works. So we will rebuild the server to dockerized version
