### ISSUE TITLE
Fatal error: CannotImportCustomDimensionException::__construct(): Argument #1 ($gaCustomDimension) must be of type Google\\Service\\Analytics\\CustomDimension

### ISSUE THREAD

**Issue by tsteur** [matomo-org/plugin-GoogleAnalyticsImporter#438]
Looks like this happens when configuring an import. See below

> 
Error: {"message":"Piwik\\Plugins\\GoogleAnalyticsImporter\\CannotImportCustomDimensionException::__construct(): Argument #1 ($gaCustomDimension) must be of type Google\\Service\\Analytics\\CustomDimension, Google\\Analytics\\Admin\\V1alpha\\CustomDimension given, called in \/plugins\/GoogleAnalyticsImporter\/Google\/GoogleGA4CustomDimensionMapper.php on line 43","file":"\/plugins\/GoogleAnalyticsImporter\/CannotImportCustomDimensionException.php","line":21,"request_id":"956d8","backtrace":" on \/plugins\/GoogleAnalyticsImporter\/CannotImportCustomDimensionException.php(21)\n#0 \/plugins\/GoogleAnalyticsImporter\/Google\/GoogleGA4CustomDimensionMapper.php(43): Piwik\\Plugins\\GoogleAnalyticsImporter\\CannotImportCustomDimensionException->__construct(Object(Google\\Analytics\\Admin\\V1alpha\\CustomDimension), 'unsupported sco...')\n#1 \/plugins\/GoogleAnalyticsImporter\/Google\/GoogleGA4CustomDimensionMapper.php(61): Piwik\\Plugins\\GoogleAnalyticsImporter\\Google\\GoogleGA4CustomDimensionMapper->mapScope(Object(Google\\Analytics\\Admin\\V1alpha\\CustomDimension))\n#2 \/plugins\/GoogleAnalyticsImporter\/ImporterGA4.php(221): Piwik\\Plugins\\GoogleAnalyticsImporter\\Google\\GoogleGA4CustomDimensionMapper->checkCustomDimensionCount(Array, Object(Google\\ApiCore\\PagedListResponse), Array)\n#3 \/plugins\/GoogleAnalyticsImporter\/Controller.php(500): Piwik\\Plugins\\GoogleAnalyticsImporter\\ImporterGA4->makeSite('properties\/1...', '', 'website', Array, true)\n#4 [internal function]: Piwik\\Plugins\\GoogleAnalyticsImporter\\Controller->startImportGA4()\n#5 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#6 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('GoogleAnalytics...', 'startImportGA4', Array)\n#7 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#8 \/index.php(25): require_once('\/c...')\n#9 {main}"

> URL: /index.php?date=yesterday&module=GoogleAnalyticsImporter&format=json&action=startImportGA4&startDate=2023-08-02&endDate=&propertyId=properties%2F....&viewId=&nonce=...&accountId=&isMobileApp=0&timezone=&extraCustomDimensions%5B0%5D%5Bga4Dimension%5D=&extraCustomDimensions%5B0%5D%5BdimensionScope%5D=&isVerboseLoggingEnabled=0&forceCustomDimensionSlotCheck=1&segment=&idSite=1&period=day

> Referrer: /index.php?module=GoogleAnalyticsImporter&action=index&date=yesterday&period=day&idSite=1

> GET: {"date":"yesterday","module":"GoogleAnalyticsImporter","format":"json","action":"startImportGA4","startDate":"2023-08-02","endDate":"","propertyId":"properties\/1...","viewId":"","nonce":"...","accountId":"","isMobileApp":"0","timezone":"","extraCustomDimensions":[{"ga4Dimension":"","dimensionScope":""}],"isVerboseLoggingEnabled":"0","forceCustomDimensionSlotCheck":"1","segment":"","idSite":"1","period":"day"}

> POST: {"token_auth":"XYZANONYMIZED","force_api_session":"1"}

**Comment by snake14** [comment]
I was unable to reproduce the issue running some GA4 imports locally. Any recommendations or idea what would be causing this @AltamashShaikh ?

**Comment by AltamashShaikh** [comment]
@tsteur @snake14 I found 2 issues
1. [Here](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/4.x-dev/Google/GoogleGA4CustomDimensionMapper.php#L43) the function expects it to be a GA3 dimension, we need to create similar class for GA4 and update that.
2. There is a new scope "item" available for GA4, which is for Ecommerce we need to handle that
![Screenshot from 2023-08-03 07-16-53](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/assets/14902277/3ac5ab89-761d-4560-8604-0693c29c6aa9)

**Comment by AltamashShaikh** [comment]
@snake14 Adding a Custom Dimension with scope:item, I can reproduce this issue
![Screenshot from 2023-08-03 07-23-07](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/assets/14902277/acb1e897-06dd-47a9-ac40-051e82806533)

**Comment by AltamashShaikh** [comment]
@tsteur @sgiehl Does it make sense to map the `scope:item` as an action dimension ?

**Comment by tsteur** [comment]
@AltamashShaikh sorry I don't know. Maybe @sgiehl or someone else does?

**Comment by sgiehl** [comment]
Hm. Good question. Matomo currently does not even allow to map dimensions to goal actions (see https://github.com/matomo-org/matomo/issues/20642). Neither is it possible to have dimensions for ecommerce items. 
I guess this is something we currently aren't able to map to Matomo.

**Comment by AltamashShaikh** [comment]
@sgiehl Should we create a ticket in core to support this or mapping as action should be fine ?

**Comment by sgiehl** [comment]
There is a related issue for core here: https://github.com/matomo-org/matomo/issues/19351
Wouldn't mapping it as action make the action dimension reports incorrect? I would actually simply ignore it for now.
You could maybe create a issue here in the plugin repo, to support item dimensions once the core issue was solved.

**Comment by AltamashShaikh** [comment]
Yes will do that :+1:

**Comment by Stan-vw** [comment]
Thanks for iterating on the possibilities here.
If we’re not able to implement a proper mapping for now, let’s fall back to the previously shelved idea of skipping the import of the item dimension. That way, people who use the item dimension can still use the GA import, albeit with a limitation. That sounds better than not being able to use it at all (for now)
