### ISSUE TITLE
backendError on the same date, two websites

### ISSUE THREAD

**Issue by lingfish** [matomo-org/plugin-GoogleAnalyticsImporter#448]
Hi, I have a strange issue where my import isn't continuing past a specific date (2016-08-23).  Keeps crashing with the same error:

```
INFO [2023-08-28 00:05:10] 363193  Importing data for GA View xxx for date 2016-08-23...
INFO [2023-08-28 00:05:11] 363193  Google Analytics API returned error: {
  "error": {
    "code": 503,
    "message": "The service is currently unavailable.",
    "errors": [
      {
        "message": "The service is currently unavailable.",
        "domain": "global",
        "reason": "backendError"
      }
    ],
    "status": "UNAVAILABLE"
  }
}
. Waiting 2s before trying again...
INFO [2023-08-28 00:05:13] 363193  Google Analytics API returned error: {
  "error": {
    "code": 503,
    "message": "The service is currently unavailable.",
    "errors": [
      {
        "message": "The service is currently unavailable.",
        "domain": "global",
        "reason": "backendError"
      }
    ],
    "status": "UNAVAILABLE"
  }
}

```

I got around it on one site by changing the end date to just before this date... on the other, I foolishly tried re-import date ranges, and it's just stuck now.

**Comment by AltamashShaikh** [comment]
@lingfish Does it shows data for 2016-08-23 or dates older then that [here](https://ga-dev-tools.google/query-explorer/) ?

We also have noticed this and looks like GA3 after sunset is returning 503 for older or last date

You can check for below report or with less dimensions and metrics
![Screenshot from 2023-08-28 06-51-46](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/assets/14902277/715c8b94-47f2-44e8-9919-504a65710aa4)

**Comment by lingfish** [comment]
Hi, yeah, it shows data:

![image](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/assets/1295960/4848c5d1-86d0-4af6-91aa-cd245cda6e83)

**Comment by AltamashShaikh** [comment]
@lingfish and if you run it for a day `2016-08-23` it still returns the data ?

**Comment by lingfish** [comment]
Fascinating!  I get an error:

```
An error has occured
Error code: 500

Error message: There was an internal error.
```

If I do a day, either side, works fine.

**Comment by AltamashShaikh** [comment]
@lingfish I didn't get you, what works ?

**Comment by lingfish** [comment]
If I do for a day `2016-08-22` or `2016-08-24` (either side of the date you requested), I get results.  I get the 500 for `2016-08-23`.

**Comment by AltamashShaikh** [comment]
Okay thanks for answering that, I think we can't do much here since Google is deprecating the API its likely be a part of that..to progress with the import, I can suggest a workaround.

Copy the option_value, by running this below query
```
Select * from matomo_option where option_name='GoogleAnalyticsImporter.importStatus_498'
```
![Screenshot from 2023-08-29 07-03-56](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/assets/14902277/82ab14eb-eb6a-4673-a482-c000d37775e7)


Now the copied option_value would be a JSON, edit the following keys `last_date_imported, main_import_progress, last_day_archived` and change the date to `2016-08-22` and update the database column and run the import again.

**Comment by lingfish** [comment]
Thanks heaps for this, figured it would be a DB update and all good there.  Done and waiting to be un-ratelimited.

Any way to also cancel re-imports I'd configured to try getting around this?

`2016-08-01,2016-12-31`

**Comment by AltamashShaikh** [comment]
@lingfish There is `reimport_ranges` key in the same option_value you can edit that

**Comment by lingfish** [comment]
Thanks, so you mean this portion:

```
    "reimport_ranges": [
        [
            "2016-08-01",
            "2016-12-31"
        ]
    ],

```
Do I delete that whole JSON array, or keep it and make it empty?

**Comment by AltamashShaikh** [comment]
@lingfish 
```
 "reimport_ranges": []
 ```

**Comment by AltamashShaikh** [comment]
@lingfish Can we close this issue ?
