### ISSUE TITLE
Error Message Backend

### ISSUE THREAD

**Issue by Mich-es** [matomo-org/plugin-GoogleAnalyticsImporter#45]
Since the latest Version, in the Backend appears a error message:

`errored
Error message: Error on day 2012-01-04, { "error": { "code": 400, "message": "Unknown metric(s): ga:totalValue, ga:transactions\nFor details see https://developers.google.com/analytics/devguides/reporting/core/dimsmets.", "errors": [ { "message": "Unknown metric(s): ga:totalValue, ga:transactions\nFor details see https://developers.google.com/analytics/devguides/reporting/core/dimsmets.", "domain": "global", "reason": "badRequest" } ], "status": "INVALID_ARGUMENT" } } `

**Comment by diosmosis** [comment]
This has happened before for another user, they were able to resolve by disabling and re-enabling ecommerce in their GA property settings. Can you see if that would work for you? If not, you'll need to reach out to GA since both of those metrics are listed in the link in the error message.

**Comment by Mich-es** [comment]
Have not changed anything - today it works again

**Comment by diosmosis** [comment]
Ok, I'll close this then.

**Comment by mattab** [comment]
Fyi we also experienced the issue (only once so far)

`Error: {"message":"{\n \"error\": {\n \"code\": 400,\n \"message\": \"Unknown metric(s): ga:totalValue, ga:transactions\\nFor details see https:\/\/developers.google.com\/analytics\/devguides\/reporting\/core\/dimsmets.\",\n \"errors\": [\n {\n \"message\": \"Unknown metric(s): ga:totalValue, ga:transactions\\nFor details see https:\/\/developers.google.com\/analytics\/devguides\/reporting\/core\/dimsmets.\",\n \"domain\": \"global\",\n \"reason\": \"badRequest\"\n }\n ],\n \"status\": \"INVALID_ARGUMENT\"\n }\n}\n","file":"\/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php","line":118,"backtrace":" on \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(118)\n#0 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\\Psr7\\Response), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#1 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Task\/Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\\Client), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#2 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(58): Google_Task_Runner->run()\n#3 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Client.php(862): Google_Http_REST::execute(Object(GuzzleHttp\\Client), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...', Array, NULL)\n#4 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Service\/Resource.php(232): Google_Client->execute(Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#5 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient-services\/src\/Google\/Service\/AnalyticsReporting\/Resource\/Reports.php(39): Google_Service_Resource->call('batchGet', Array, 'Google_Service_...')\n#6 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Google\/GoogleAnalyticsQueryService.php(157): Google_Service_AnalyticsReporting_Resource_Reports->batchGet(Object(Google_Service_AnalyticsReporting_GetReportsRequest), Array)\n#7 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Google\/GoogleAnalyticsQueryService.php(100): Piwik\\Plugins\\GoogleAnalyticsImporter\\Google\\GoogleAnalyticsQueryService->gaBatchGet(Object(Piwik\\Date), Array, Array, 'ga:sessions')\n#8 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Importers\/Resolution\/RecordImporter.php(67): Piwik\\Plugins\\GoogleAnalyticsImporter\\Google\\GoogleAnalyticsQueryService->query(Object(Piwik\\Date), Array, Array)\n#9 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Importers\/Resolution\/RecordImporter.php(25): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importers\\Resolution\\RecordImporter->queryScreenResolution(Object(Piwik\\Date))\n#10 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Importer.php(432): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importers\\Resolution\\RecordImporter->importRecords(Object(Piwik\\Date))\n#11 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Importer.php(369): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importer->importDay(Object(Piwik\\Site), Object(Piwik\\Date), Array, '')\n#12 \/var\/www\/html\/plugins\/GoogleAnalyticsImporter\/Commands\/ImportReports.php(243): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importer->import('3', 'xxxxxxx', Object(Piwik\\Date), Object(Piwik\\Date), Object(Piwik\\Plugins\\GoogleAnalyticsImporter\\ImportLock))\n#13 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Command\/Command.php(257): Piwik\\Plugins\\GoogleAnalyticsImporter\\Commands\\ImportReports->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(874): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(195): Symfony\\Component\\Console\\Application->doRunCommand(Object(Piwik\\Plugins\\GoogleAnalyticsImporter\\Commands\\ImportReports), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 [internal function]: Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 \/var\/www\/html\/core\/Console.php(140): call_user_func(Array, Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 \/var\/www\/html\/core\/Access.php(644): Piwik\\Console->Piwik\\{closure}()\n#19 \/var\/www\/html\/core\/Console.php(141): Piwik\\Access::doAsSuperUser(Object(Closure))\n#20 \/var\/www\/html\/core\/Console.php(93): Piwik\\Console->doRunImpl(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 \/var\/www\/html\/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(126): Piwik\\Console->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 \/var\/www\/html\/console(32): Symfony\\Component\\Console\\Application->run()\n#23 {main}"}`


and another time for another customer it failed with the following slightly different message:

`Error: {"message":"{\n \"error\": {\n \"code\": 400,\n \"message\": \"Unknown metric(s): ga:goal1ConversionRate, ga:goal1Completions, ga:goal3Value, ga:goal2Completions, ga:goal3Completions, ga:goal1Value, ga:goal2ConversionRate, ga:goal2Value, ga:goal3ConversionRate\\nFor details see https:\/\/developers.google.com\/analytics\/devguides\/reporting\/core\/dimsmets.\",\`

**Comment by diosmosis** [comment]
@mattab this seems to happen randomly. I guess we can just retry, but you should expect the GA API to fail, and sometimes repeatedly.

**Comment by tsteur** [comment]
just for referencing pasting another one:

> Error: {"message":"{\n \"error\": {\n \"code\": 400,\n \"message\": \"Unknown metric(s): ga:goal5Value, ga:goal5ConversionRate, ga:goal5Completions, ga:transactionRevenue\\nFor details see https:\/\/developers.google.com\/analytics\/devguides\/reporting\/core\/dimsmets.\",\n \"errors\": [\n {\n \"message\": \"Unknown metric(s): ga:goal5Value, ga:goal5ConversionRate, ga:goal5Completions, ga:transactionRevenue\\nFor details see https:\/\/developers.google.com\/analytics\/devguides\/reporting\/core\/dimsmets.\",\n \"domain\": \"global\",\n \"reason\": \"badRequest\"\n }\n ],\n \"status\": \"INVALID_ARGUMENT\"\n }\n}\n","file":"\/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php","line":118,"backtrace":" on \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(118)\n#0 \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\\Psr7\\Response), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#1 \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Task\/Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\\Client), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#2 \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Http\/REST.php(58): Google_Task_Runner->run()\n#3 \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Client.php(862): Google_Http_REST::execute(Object(GuzzleHttp\\Client), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...', Array, NULL)\n#4 \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient\/src\/Google\/Service\/Resource.php(232): Google_Client->execute(Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#5 \/plugins\/GoogleAnalyticsImporter\/vendor\/google\/apiclient-services\/src\/Google\/Service\/AnalyticsReporting\/Resource\/Reports.php(39): Google_Service_Resource->call('batchGet', Array, 'Google_Service_...')\n#6 \/plugins\/GoogleAnalyticsImporter\/Google\/GoogleAnalyticsQueryService.php(164): Google_Service_AnalyticsReporting_Resource_Reports->batchGet(Object(Google_Service_AnalyticsReporting_GetReportsRequest), Array)\n#7 \/plugins\/GoogleAnalyticsImporter\/Google\/GoogleAnalyticsQueryService.php(106): Piwik\\Plugins\\GoogleAnalyticsImporter\\Google\\GoogleAnalyticsQueryService->gaBatchGet(Object(Piwik\\Date), Array, Array, 'ga:sessions')\n#8 \/plugins\/GoogleAnalyticsImporter\/Importers\/Resolution\/RecordImporter.php(34): Piwik\\Plugins\\GoogleAnalyticsImporter\\Google\\GoogleAnalyticsQueryService->query(Object(Piwik\\Date), Array, Array)\n#9 \/plugins\/GoogleAnalyticsImporter\/Importers\/Resolution\/RecordImporter.php(26): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importers\\Resolution\\RecordImporter->queryConfig(Object(Piwik\\Date))\n#10 \/plugins\/GoogleAnalyticsImporter\/Importer.php(432): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importers\\Resolution\\RecordImporter->importRecords(Object(Piwik\\Date))\n#11 \/plugins\/GoogleAnalyticsImporter\/Importer.php(369): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importer->importDay(Object(Piwik\\Site), Object(Piwik\\Date), Array, '')\n#12 \/plugins\/GoogleAnalyticsImporter\/Commands\/ImportReports.php(243): Piwik\\Plugins\\GoogleAnalyticsImporter\\Importer->import('2', 'xxxxxx', Object(Piwik\\Date), Object(Piwik\\Date), Object(Piwik\\Plugins\\GoogleAnalyticsImporter\\ImportLock))\n#13 \/vendor\/symfony\/console\/Symfony\/Component\/Console\/Command\/Command.php(257): Piwik\\Plugins\\GoogleAnalyticsImporter\\Commands\\ImportReports->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 \/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(874): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 \/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(195): Symfony\\Component\\Console\\Application->doRunCommand(Object(Piwik\\Plugins\\GoogleAnalyticsImporter\\Commands\\ImportReports), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 [internal function]: Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 \/core\/Console.php(140): call_user_func(Array, Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 \/core\/Access.php(644): Piwik\\Console->Piwik\\{closure}()\n#19 \/core\/Console.php(141): Piwik\\Access::doAsSuperUser(Object(Closure))\n#20 \/core\/Console.php(93): Piwik\\Console->doRunImpl(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 \/vendor\/symfony\/console\/Symfony\/Component\/Console\/Application.php(126): Piwik\\Console->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 \/console(32): Symfony\\Component\\Console\\Application->run()\n#23 {main}"}

**Comment by diosmosis** [comment]
@tsteur what is the desired behavior when these errors are encountered on cloud? Ignore/don't report an error?

**Comment by tsteur** [comment]
I'd say for now we just ignore it if it happens only once randomly. If it happens repeatedly then we may need to investigate

**Comment by diosmosis** [comment]
@tsteur these are GA API errors, I don't think there's anything we can really investigate (it says the metrics are invalid, but they are listed as valid in the GA API docs; eventually, like the next day, they might stop occurring). I'll just retry/ignore and if the API is unreachable, it will stop the import but not throw an exception so cloud doesn't get emails.

**Comment by diosmosis** [comment]
Fixed by #119
