### ISSUE TITLE
Import data killed - long-running PHP processes

### ISSUE THREAD

**Issue by Stevie0130** [matomo-org/plugin-GoogleAnalyticsImporter#494]
Hi I have a problem with the long-running PHP processes. I host my data with the webhoster all-inkl and have set the PHP settings to **max_execution_time to 0** and **memory_limit to 512M** in the ".user.ini" file. However, I still receive the error message. I am currently using PHP version 8.2.13. But I had the same problem with 8.1 and 8.0 as well. What can I do? I just can't get the importer to work. Does anyone have an idea?

**Comment by AltamashShaikh** [comment]
@Stevie0130 Have you enabled archiving ? If not you can refer to this [doc](https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/#:~:text=If%20you%20are%20using%20Matomo,that%20will%20execute%20every%20hour.) to set it up.

The archiving can restart the process automatically.

**Comment by Stevie0130** [comment]
@AltamashShaikh yes, I added webcron today and set the execution to 15 minutes. Unfortunately, the import still aborts. The cron job does run, but it has no effect.

**Comment by AltamashShaikh** [comment]
@Stevie0130 This issue looks like specific to your webhosting platform, and looks like your ini_settings are not being respected by your hosting provider, can you please check with them on how to run long running task ?

**Comment by Stevie0130** [comment]
@AltamashShaikh I asked the support and received the following answer: "The value you have used is set as localvalue in the max_execution_time and thus affects the execution time of the PHP scripts accordingly." So, everything should be correct here. Do you have any other ideas?

**Comment by AltamashShaikh** [comment]
@Stevie0130 Reading on how to setup cronjobs in `all-inkl`, it looks like it supports a webcron and that webcron might be timing out after certain period and that is leading to your import being killed.

I am afraid we couldn't help you much here, you might need to contact the support and explain them the issue, they would be able to help you better here

**Comment by AltamashShaikh** [comment]
@Stevie0130 Can we close this ticket?

**Comment by Stevie0130** [comment]
@AltamashShaikh Yes, thank you for your help!
