### ISSUE TITLE
Merging GA4 and Universal Analytics data within the same site ID within Matomo

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/plugin-GoogleAnalyticsImporter#510]
Hi team,

When importing GA4 data and Universal Analytics data, it is creating two site ID within Matomo.
Wouldn't there be a way to merge the twos so that we can get only one site ID and get the migration done?

Thank you,

**Comment by snake14** [comment]
Hi @Chardonneaur . As this sounds like a similar request to #2 , I'm going to go ahead and close it as a duplicate.

GA Importer only allows creating a new site for each import. I'm not aware of a way to merge sites. Any further thoughts @AltamashShaikh ?

**Comment by AltamashShaikh** [comment]
@snake14 We currently don't have a way to import into existing siteID, but we would want to add it in future as stated in #2.
