### ISSUE TITLE
Error after update from 1.1.2 to 1.2

### ISSUE THREAD

**Issue by minimeee** [matomo-org/plugin-GoogleAnalyticsImporter#53]
Hi!

 I've installed GA importer yesterday, started to import GA data (worked, but not yet finished) and updated the importer to 1.2 today. Since then, I always get the following error when trying to open the "Google Analytics Importer" page:

```
Key "days_finished_since_rate_limit" for array with keys "status, idSite, ga, last_date_imported, import_start_time, import_end_time, last_job_start_time, last_day_archived, import_range_start, import_range_end, extra_custom_dimensions, site, estimated_days_left_to_finish, gaInfoPretty" does not exist.
in /var/www/matomo/plugins/GoogleAnalyticsImporter/templates/index.twig line 195
```
![Matomo_Error](https://user-images.githubusercontent.com/5322305/71153724-29071900-223a-11ea-9769-bec5b1980f34.png)
I already restarted nginx (as suggested) but that didn't help. The only other plugin I've installed is "TasksTimetable" (3.0.2). My Matomo installation is only 2 days old and worked fine so far.

What can I do to repair the plugin and continue importing?

**Comment by diosmosis** [comment]
The import will still run in the background, this is just an issue w/ the reporting page. I'll put in a fix shortly.

**Comment by diosmosis** [comment]
This should be fixed in 1.2.1. It'll take a bit for the marketplace to put it up, but once it does, let me know if it works for you.

**Comment by minimeee** [comment]
Your fix seems to work. Thanks a lot for your fast response!

**Comment by diosmosis** [comment]
No problem, let us know if you encounter any other issues.
