### ISSUE TITLE
Remove UA (GA3) import option

### ISSUE THREAD

**Issue by 9joshua** [matomo-org/plugin-GoogleAnalyticsImporter#532]
With the end of GA3 data and API access, the option to import this data from the GA Import tool should be removed.

I can still connect to my GA3 account but no data is imported despite the status showing 'ongoing'. This will only lead to confusion for users.
![image](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/assets/20234985/e05a409c-f8bd-4531-9996-394d8fe307a3)
![image](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/assets/20234985/34f6f7bf-b913-4f54-a44e-ef3ef76485ce)

**Comment by snake14** [comment]
Thank you for taking the time to create this issue @9joshua . I don't know if we want to completely hide the ability to import from UA just yet. I ran an import for a past date range using the console command and it appeared to run correctly. Maybe we should disable the ability to create new UA imports without an end date. What do you think @AltamashShaikh ?

**Comment by AltamashShaikh** [comment]
@snake14 For me the import ran successfully, but the API is not returning any results for me we should disable the ability to create new imports for GA3 :+1:
