### ISSUE TITLE
OAuth doesn't work behind a proxy / Plugin doesn't use proxy configuration

### ISSUE THREAD

**Issue by peterbo** [matomo-org/plugin-GoogleAnalyticsImporter#68]
When behind a proxy, OAuth doesn't work, because the request back to google fails. This is because, as far as I understood, uses its own implementation of making this request and therefore doesn't use the configured proxy.

**Comment by eschultz-magix** [comment]
As a workaround, you can set ```HTTPS_PROXY``` as environment variable. Case matters. This variable is respected by Guzzle, which is used in the background. If you are using nginx with php-fpm, you have to set ```env[HTTPS_PROXY]``` in ```/php/<version>/fpm/pool.d/www.conf``` because nginx clears all environment variables by default.

**Comment by rolfcronberg** [comment]
I have the same problem, running Apache on Debian. I can access google with curl from this server with HTTPS_PROXY in environment but not from the plugin. 

![bild](https://user-images.githubusercontent.com/17985774/132837515-378f6554-6911-4cf3-a981-c612becb67a4.png)

![bild](https://user-images.githubusercontent.com/17985774/132837900-e8380132-a667-4249-bd44-23f375c148a9.png)

If anyone have an idea?

**Comment by sgiehl** [comment]
I have prepared some changes that might fix the issue. But as I haven't set up the Google importer locally, nor do I use a proxy, I'm not able to test that. Is anyone able to apply the changes in https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/pull/202 and can check if that helps

**Comment by rolfcronberg** [comment]
I'll take a look at it to morrow.

**Comment by bhayden-umn** [comment]
@sgiehl I came here to open a PR on this issue. Tried the code in #202 and it does work with minor changes, which I noted in a review on 202.

**Comment by snake14** [comment]
@machinehum Thank you for your assistance. The PR has been merged and the changes should be released as part of our usual plugin release cycle in a little over a week.
