### ISSUE TITLE
Having the plugin installed makes the dashboard unusable

### ISSUE THREAD

**Issue by ampaze** [matomo-org/plugin-GoogleAnalyticsImporter#76]
Ever since we installed this plugin, the dashboard cannot be used, as matomo now thinks the users don't have the right permissions. The admin sections still works fine.

This is what it looks like, basically an empty page (btw. the message itself is also wrong, as the real one gets replaced with a more generic one)

![image](https://user-images.githubusercontent.com/758593/81192216-3ab74600-8fba-11ea-92ca-0f7f79c3064e.png)

I figured this out by downloading a fresh copy of matomo and copied over the config. That version works, and the only difference is the installed plugins. When I copy this plugin over to the fresh copy, it shows the same error. When I remove it, it works again.

**Comment by diosmosis** [comment]
Hi @ampaze, sorry you're experiencing this problem. Could you tell me whether you still experience the issue if you leave the plugin installed in matomo, but deactivate the plugin in the plugin management admin page?

Do you have any imported sites at present? If yes, then while he plugin is activated, if you enter an idSite in the URL manually for a site that is not imported, does it load?

**Comment by ampaze** [comment]
Thanks for getting back to me.

The importer is currently still in progress, will I lose data when I deactivate the plugin?

I have two siteIds, the one currently beeing imported and the initial one that is currently tracking the page. The dashboard does not work for any siteId I enter.

**Comment by diosmosis** [comment]
> The importer is currently still in progress, will I lose data when I deactivate the plugin?

The import command will fail on the day it's currently importing, however afterwards you should be able to resume from that day. To be safe, however, you can wait until the import job says it's been rate limited (or killed if you're on shared hosting and the hoster doesn't like long running processes).

> I have two siteIds, the one currently beeing imported and the initial one that is currently tracking the page. The dashboard does not work for any siteId I enter.

This is strange. This plugin doesn't change permissions in any way, so it shouldn't have an effect in this regard... It's possible the error being covered up is of more use. Do you have any other third party plugins installed (ie, plugins that are not authored by Matomo.org or InnoCraft)?

One other thing you could try is enabling debug logging (see https://matomo.org/faq/troubleshooting/faq_115/) and triggering the error. The real cause might get logged.

**Comment by ampaze** [comment]
When I deactivate the GoogleAnalyticsImporter Plugin, the dashboard is working again.

The real error message is _ExceptionPrivilegeAccessWebsite_

> "You can't access this resource as it requires 'view' access for the website id = 1"

The only other additional plugin is **InvalidateReports**, but with my fresh copy it is enough to copy the GoogleAnalyticsImporter Plugin to make the dashboard fail. So I am pretty sure the problem is somewhere in GoogleAnalyticsImporter.

I tried debug logging, but it only says the same thing as in the screenshot above. So no more details.

**Comment by diosmosis** [comment]
@ampaze there's no stack trace in the logs? If not, can you change this code/file (after making a backup): https://github.com/matomo-org/matomo/blob/3.13.5/core/testMinimumPhpVersion.php#L85-L97 to:

```
    function Piwik_ShouldPrintBackTraceWithMessage()
    {
        return true;
    }
```

then trigger the error? There should be a stack trace either on the screen or the logs. Then change the file back to the backup.

**Comment by ampaze** [comment]
This is what the log says:

ERROR API[2020-05-07 13:02:33 UTC] [d5ed7] Uncaught exception in API: Ihre Sitzung ist aufgrund Inaktivität abgelaufen. Bitte melden Sie sich an um fortzufahren. /home/www/matomo/core/Access.php:728

even with the Piwik_ShouldPrintBackTraceWithMessage changes, no stack trace in the log file.

But the error message in the browser / xhr is now this

```
{"result":"error","message":"Ihre Sitzung ist aufgrund Inaktivit\u00e4t abgelaufen. Bitte melden Sie sich an um fortzufahren. 
#0 \/home\/www\/matomo\/core\/Access.php(536): Piwik\\Access-&gt;throwNoAccessException('Ihre Sitzung is...') 
#1 \/home\/www\/matomo\/core\/Piwik.php(506): Piwik\\Access-&gt;checkUserHasViewAccess(Array) 
#2 \/home\/www\/matomo\/plugins\/API\/API.php(382): Piwik\\Piwik::checkUserHasViewAccess('1') 
#3 [internal function]: Piwik\\Plugins\\API\\API-&gt;getWidgetMetadata('1') 
#4 \/home\/www\/matomo\/core\/API\/Proxy.php(237): call_user_func_array(Array, Array) 
#5 \/home\/www\/matomo\/core\/Context.php(28): Piwik\\API\\Proxy-&gt;Piwik\\API\\{closure}() 
#6 \/home\/www\/matomo\/core\/API\/Proxy.php(328): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure)) 
#7 \/home\/www\/matomo\/core\/API\/Request.php(266): Piwik\\API\\Proxy-&gt;call('\\\\Piwik\\\\Plugins\\\\...', 'getWidgetMetada...', Array) 
#8 \/home\/www\/matomo\/plugins\/API\/Controller.php(41): Piwik\\API\\Request-&gt;process() 
#9 [internal function]: Piwik\\Plugins\\API\\Controller-&gt;index() 
#10 \/home\/www\/matomo\/core\/FrontController.php(590): call_user_func_array(Array, Array) 
#11 \/home\/www\/matomo\/core\/FrontController.php(165): Piwik\\FrontController-&gt;doDispatch('API', false, Array) 
#12 \/home\/www\/matomo\/core\/dispatch.php(34): Piwik\\FrontController-&gt;dispatch() 
#13 \/home\/www\/matomo\/index.php(27): require_once('\/home\/www\/matom...') 
#14 {main}"}

**Comment by diosmosis** [comment]
@ampaze would you be willing to provide access to your matomo for further debugging? (if yes, create a new user you'll delete later and email benaka@innocraft.com w/ the temporary credentials)? If not I'll reply w/ some other things to try. (make sure the user has access to both sites)

**Comment by ampaze** [comment]
I think it would be easier for me to try some more things first.

**Comment by diosmosis** [comment]
@ampaze If `getWidgetMetadata()` is failing it might be that the session isn't being recognized (it looks like it thinks no one is logged in). Some things to try:

- try logging in and viewing the page in an incognito window
- try deactivating other plugins to see if the problem has something to do with the deactivation process
- try to reproduce it on the empty matomo you setup (if you can, and are willing to provide access to that matomo rather than you're actual one, I can use that as well to debug)
- try to temporarily add anonymous access to a site you can't access normally (a new site would work if you can reproduce the problem w/ a new site)

And if you could let me know what version of matomo you're using and what version of the plugin, that would help.

**Comment by ampaze** [comment]
Sorry I was absent from this issue for a while. Your suggestions were mostly stuff I already tried and had also written about here. We are now waiting for the import to finish and then remove the plugin.
