### ISSUE TITLE
Error when executing Google Analytics Import through SSH console terminal

### ISSUE THREAD

**Issue by tiurlumbangaol** [matomo-org/plugin-GoogleAnalyticsImporter#8]
Error when executing Google Analytics Import through SSH console terminal, with this command :

`./console googleanalyticsimporter:import-reports --property=UA-XXXXXXXX-X --view=XXXXXXXX --dates=2019-09-01`

the error saying :  
Fatal error: Class 'Piwik\SettingsServer' not found in /home2/softbless/analytics.softbless.com/core/testMinimumPhpVersion.php on line 87

I'm using Matomo Beta 3.12.0-b4 version.

**Comment by diosmosis** [comment]
This looks like a different error occurred early on and the fatal error is covering it up. In the `testMinimumPhpVersion.php` file, can you temporarily change the `Piwik_ShouldPrintBackTraceWithMessage` function to:

```
function Piwik_ShouldPrintBackTraceWithMessage()
{
    return true;
}
```

and run the command w/ `-vvv`?

**Comment by tiurlumbangaol** [comment]
hi.
the output is now : 

> To run Matomo you need at least PHP version 5.5.9

Unfortunately it seems your webserver is using PHP version 5.4.45.

Please try to update your PHP version, Matomo is really worth it! Nowadays most web hosts
support PHP 5.5.9.

Also see the FAQ: My Web host supports PHP4 by default. How can I enable PHP5?

-------------------------
I install matomo on hostgator hosting, then i change the version to become : 5.6.30
i tried on shell : php -v it gave output : 
PHP 5.6.30 (cli) (built: Mar 27 2017 11:48:20)
so i dont know why, even i updated the php version, it's stiil taking the older php version...

please help

**Comment by Findus23** [comment]
Hi,

Honestly this is something the support of your host can help you better with.
But maybe instead of executing it directly (`./console`), specify the exact php executable (`php ./console`). This way you can be sure it uses the same PHP as when you run `php -v`.

**Comment by tiurlumbangaol** [comment]
hi @Findus23 
thanks a lot for the tips! it is really helpful for me. and it's working.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/error-on-ga4-import/47441/2
