### ISSUE TITLE
Unable to import OAuth Client configuration

### ISSUE THREAD

**Issue by tomaxuser** [matomo-org/plugin-GoogleAnalyticsImporter#80]
Reposting <https://forum.matomo.org/t/google-analytics-importer-unable-to-import-oauth-client-configuration/37637> here:

I am trying to import a website from Google Analytics into Matomo, however, I’ve got stuck on step 2.2.3 from https://matomo.org/docs/google-analytics-importer/.

When I try to import the OAuth Client configuration file, either as a file, or pasting its contents into the Configuration Text field, after pressing Save, the page gets reloaded to an empty form without any message or visible change.

So far I have failed to locate any hint pointing to whatever may have gone wrong: there’s nothing in webserver’s access/error log, nothing that seems relevant in Piwik log (even when increasing verbosity in `config.ini.php` to `DEBUG`), nor do I see anything interesting in the Firebug network requests log (like failing HTTP codes).

AFAICT the OAuth Client configuration JSON file that I have received looks sound.

For the purpose of using the GoogleAnalyticsImporter plugin I had to enable the Login plugin (if I remember correctly – we normally use LoginLdap). I tried to temporarily disable LoginLdap, in case it is causing the trouble, but that didn’t seem to change anything. I also believe I meet all the requirements mentioned in the importer docs page.

I am running latest Matomo 3.13.6 with latest Google Analytics Importer 1.4.0.

Any hints as to what I might be doing wrong or what should I try?

**Comment by diosmosis** [comment]
When it redirects to the same page after uploading, can you check if the URL is different or if there's an `error=` URL parameter?

If you have access to your mysql DB, can you run this command and see what it returns (after trying to upload config): `SELECT option_value FROM {tables_prefix}option WHERE option_name = 'GoogleAnalyticsImporter.clientConfiguration'`? (replace `{tables_prefix}` with the table prefix you installed Matomo with.

**Comment by tomaxuser** [comment]
Re the URL, I get back to the original page (after 302). Re the SQL, it returns one row with empty string.

I have tried to do some simple debugging with `throw`s in `Controller.php` (I guessed it's the right place) and it seems I do not get inside [the condition block](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/1.4.0/Controller.php#L162) (EDIT: although I am uploading the file) and the [`validateConfig`](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/1.4.0/Controller.php#L181) gets passed an empty string.

Thanks for the fast response!

**Comment by diosmosis** [comment]
Hmm, odd (and yep Controller.php is the right place)... Debugging w/ `throw`s should work provided you remove the try-catch first (https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/1.4.0/Controller.php#L159 + https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/1.4.0/Controller.php#L183-L185).

If it's not getting into the `if`, then it can't find the uploaded json file. Do you still get an empty string in validateConfig when you paste the text instead of uploading a file? If so, can you check that the `client` query parameter is in the HTTP request with `action=configureClient` in the network requests log?

**Comment by tomaxuser** [comment]
Sure, I took care so that the try-catch block wouldn't interfere, although I could have removed it. (I have working skills with Perl, although almost none with PHP.) But I think we are getting to the root now:

In the last comment I only tried to use the file entry method. I had a look into PHP documentation regarding `$_FILES` and it looks like my problem was due to unset [`upload_tmp_dir`](https://www.php.net/manual/en/ini.core.php#ini.upload-tmp-dir) in `php.ini`: when I set it to a newly-created directory accessible to Apache, after uploading the file, I got to the next form in web UI. That is strange though, because the default for `upload_tmp_dir` looks to be `/tmp` (confirmed by `sys_get_temp_dir`) which should work fine, imho.

Before this I also tried using the text entry method and the OAuth config was visible in DB, although only after working through the above it became clear to me that it probably isn't ok that it is entity encoded.

I guess the problem with upload dir could maybe be checked for on System Check page (I see there already is something for GAI) and as to the encoding, I am not sure.

If you'd need more help with debugging, let me know. Anyway, I appreciate your support.

**Comment by diosmosis** [comment]
> Before this I also tried using the text entry method and the OAuth config was visible in DB, although only after working through the above it became clear to me that it probably isn't ok that it is entity encoded.

Entity encoded how (URL encoded or HTML encoded)? Is the value encoded in `$_POST['client']`? If it is, it should not be and I'd guess something in your apache config is doing that.

**Comment by tomaxuser** [comment]
Sorry for the later response, I had to take care of importing a website. In the meantime we have upgraded to 3.14.0 and 1.4.1.

It is the HTML entity encoding: `<` → `&lt;` and so.

When importing the OAuth config using the text entry method, dumping of `$_POST['client']` and `$client` around [line 160](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/1.4.1/Controller.php#L160) and dumping of `$client` after [the `try` block](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/1.4.1/Controller.php#L185) yields exactly the same string as was entered, so it looks ok there.

I tried to follow the path of the option up to [the `UPDATE` query](https://github.com/matomo-org/matomo/blob/3.14.0/core/Option.php#L186), but (not being knowledgeable about PHP) I didn't spot a suspicious place there. Anyway, it is strange that the file input worked when [the path](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/blob/1.4.1/Controller.php#L181-L182) for the file/text input should be the same in the end...

**Comment by diosmosis** [comment]
@tomaxuser I see, this should be an easy fix, after line 160 that you linked to, can you add the following code:

```
$config = Common::unsanitizeInputValue($config);
```

and see if it works for you?

**Comment by tomaxuser** [comment]
Thanks! That seems to work. Will this be included in the next update? In that case I'd leave that line there.

And re the problem with the file input: would it make sense to you to add a check suggested in https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/issues/80#issuecomment-650594808? I am not sure about the cause of the inability to use the `/tmp` as `upload_tmp_dir` (yet), but I guess it might help some users of this plugin.

**Comment by diosmosis** [comment]
> Will this be included in the next update?

Yes.

> would it make sense to you to add a check suggested in #80 (comment)?

If we find time to add it, that is a diagnostic we'd add to core rather than this plugin, since it would affect more than this plugin and this plugin has an alternative method to set the client config (now that it's working).

**Comment by diosmosis** [comment]
Fixed by #92
