### ISSUE TITLE
Add a DI setting to limit endDate 

### ISSUE THREAD

**Issue by tsteur** [matomo-org/plugin-GoogleAnalyticsImporter#89]
Since adding https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/pull/86/files this should be probably easy.

We'd basically need to set to force a specific endDate in https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/pull/86/files#diff-45fa769832b0e4e03d179befdbf5324dR22

The goal is basically to prevent ongoing import. We want to be able to have only an initial import of historical data up to "today", and then stop.

Was thinking we could then move https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/pull/86/files#diff-45fa769832b0e4e03d179befdbf5324dR32-R51 into DI as well as part of Matomo for WordPress but actually we want to have this code still in this plugin itself as each plugin is supposed to make itself compatible with Matomo for WordPress. Could be moved into default DI today.

When a max end date is forced, ideally we adjust the help description of the endDate field in 
![image](https://user-images.githubusercontent.com/273120/88596066-5eb98d80-d0b8-11ea-8cee-f8fbe2650734.png) to say "The forced max end date will be XYZ".

@diosmosis any chance you can have a look at this one in the next 2 weeks?

**Comment by diosmosis** [comment]
Fixed by #91
