### ISSUE TITLE
adding row to table with empty label

### ISSUE THREAD

**Issue by tiurlumbangaol** [matomo-org/plugin-GoogleAnalyticsImporter#9]
Hi, i run my google analytics import, until 2012-2014 is working well, but it got error lately, the error is : 

INFO [2019-10-20 11:40:40] 105  Importing data for GA View xxxx for date 2015-04-04...
Running archiving for newly imported data...nohup: ignoring input and redirecting stderr to stdout

Fatal error: Class 'Piwik\SettingsServer' not found in /home2/xxxx/analytics.xxxx.com/core/testMinimumPhpVersion.php on line 87

  [Exception]
  Unexpected error: adding row to table with empty label in Piwik\Plugins\GoogleAnalyticsImporter\Importers\Referrers\RecordImporter: false

**Comment by tiurlumbangaol** [comment]
solved by using solution from issue #8

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/error-on-ga4-import/47441/2
