### ISSUE TITLE
Link to the GA importer guide from the app

### ISSUE THREAD

**Issue by tsteur** [matomo-org/plugin-GoogleAnalyticsImporter#96]
I just went to the GA importer page and noticed this screen

![image](https://user-images.githubusercontent.com/273120/89237453-4bbe3480-d647-11ea-99cf-90d7fdfb5981.png)

There weren't any instructions on how to get started. I suppose a link to https://matomo.org/docs/google-analytics-importer/ with all the instructions would help?

**Comment by diosmosis** [comment]
Fixed by #97
